import pygame
import time
import os

init pygame()
mac_gsound = pygame.mixer.Sound("sounds/big_mac_g.wav")
mac_o_sound = pygame.mixer.Sound("sounds/big_mac_o.wav")
st_pep_enjoy_sound = pygame.mixer.Sound("sounds/stpepsi.wav")
tides_sound = pygame.mixer.Sound("sounds/tides.wav")
come_down_sound = pygame.mixer.Sound("sounds/c_down.wav")
tape_sound = pygame.mixer.Sound("sounds/sacred_t.wav")
wavestep_sound = pygame.mixer.Sound("sounds/step.wav")
hyper_obj_sound = pygame.mixer.Sound("sounds/hyp_obj.wav")
ecoz_sound = pygame.mixer.Sound("sounds/ecozones.wav")
cyb_slum_sound = pygame.mixer.Sound("sounds/slums.wav")
moon_sound = pygame.mixer.Sound("sounds/surf.wav")
drain_sound = pygame.mixer.Sound("sounds/brain.wav")

def brain_drain_art():
    print("WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW")
    print("WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW")
    print("WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW")
    print("WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW")
    print("WWWWXOxdxOXWWWKOOOKNXOOOKNN0OOKNWNKOOKNWWWWWNKOOOOO0XWWWWN0OOO0XWWWX0OOOOO0XNWWWWN0OOO0XWWWWX0OOOOO0XWWWX0OOOOOO0NWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW")
    print("WWNx;'...':kNNd''.lXx''.lXK:.';OWKc''cXWWWWWXc.''''';oXWW0:''.'xWWWO,.''''';oKWWW0;.'.,kWWWWO,.''''';dXWO;.''''.;OWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW")
    print("WWx,..,c,..;OWd...cXx'..lXK:...cKK:..cXWWWWWXc...,,'.'dNWk,....lNWWO,..';,'..dNWWx'....oNWNWO,..';,..'xWO,..';c:lKWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW")
    print("WNo...oXx'.,kNd...cXx'..lXK:...'d0c..cXWWWWWXc..'dx'..lNNo.....:KWWk,..;Ox,..lXWNo.....cKWWWO,..;Od'..dWO,..;ONNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW")
    print("WWk,..;x0000XNd...cXx'..lXK:....;d:..cKWWWWWXc..'xk,..lNKc.'''.,OWWk,..;0k,..lXWK:.'''.,OWWWO,..:0x'.'dWO,..;x0KWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW")
    print("WWNx,..';oKWWNd...cXx'..lXK:.....,,..cKWWWWWXc..'::'..oNO;.,:,.'dNWO,..':;..;kNWO,.,:,.'xWWWO,..:0x'.'dWO,...''lNWWWWWWW0ddKWWNNNNWWNNNNWWWNNNWNNNWNNWNNNNNNNWWNNNWWWWNNWWNNWNNNWNNW")
    print("WWWN0o;...;kNNd...cXx'..lXK:..,,.....cKWWWWWXc.......:OWx'.;o;..lXMO,...'...:OWWx'.:o;..lXMMO,..:0x'.'dWO,..';:dNWWWWWWX: ;0MKl,;;dOc,;;dN0:,dNx,dx;o0lckl,;;xO:,;:kNk;;kNd;xd,d0clX")
    print("WN0kkO0d,..;ONd...cXx'..lXK:..cd,....cXWWWWWXc..':ookKWNo..,c,..;0Wk,..;xo'..lXXl..;c,..:0MMO,..:0x'.'dWO,..;ONNWWWWWWWd..xWW0,.:.,d,.c.,0d. ;Ko.lo..l,'d,.:.,o.'c.:0c..lKc.ol..l';K")
    print("WXl..;0Xl..'dNd'..c0d'..lX0:..cKd'...cKWWWWWXc..'xWWWWWK:.......,kWk,..:0O,..cX0:.......,kWWO,..;Od'.'dNO,..;kXXXNWWWW0, cXWW0,.'.:x,.'.:0c..'ko.co....,d,.l',o..'.lO;..;0c.ol....;K")
    print("WNd'.':c,..,kWx'..';,..'dN0:..cXKc...cKWWWWWXc..'xWWWWWO,.';:,...oNk,..;0O,..cXk,..;:,..'dXNO,..';,..'xWO,..',;;c0WWWNl.'OWWWK,.:',d,.:.;x,...oo.co.,, ,d,.l';o.':.:d...'xc.ol.;' ;K")
    print("WWKo,....';kNWXx;'....,dXWK:.'cXWO;''cXWWWWWXl'',xWWWWWx'.,kNd'.'cKk,'.:0K:..:0x'.,kNd'.'lOXk;'''''';dXMO;.''''.;OWWWk'.oNWWWK;.'.:x,,d;,c',;.cl.lo.ox.,d;.'.lx';d',:.,'.lc.ol.dd.;K")
    print("WWWNKkxxxOXWWWWWXOxxxkKWWWN0OOKNWNKOOKNWWWWWNKOO0XWWWWWKOO0NWXOOO0NX0OO0NNKOO0XKOO0NWXOOO0XNX0OOOOO0XWWWN0OOOOOO0NWWWKOOXWWWWN0OkOXN00X0O0OKXO0KOKKOKN00X0kO0XXO0X0O0OXKO00OKKOXN00N")
    print("WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW")
    print("WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW")
    print("WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW")
    print("WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW")
    print("NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXXXNNXNNXNNNNNWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXKNNNXXXXXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN")
    print("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX0kOKXK0K0k0NNNNNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKkk000K0kkO0KKKXKKKKKKXKKKKKKKKKKKKKKKKKKKKKKKKKKKKK")
    print("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXK0OOKKXXK0k0XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKK0kxoodkO0KXXXXXXXXXXXXXXXKOkO0KKKkxxolldk0KKKKXXXKKKKKKKKKKKKKKKKKKKKKKKKKKKK")
    print("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKKOOKKKXXKkOXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXOdc;,''',;lkKXXXXXXXXXXXXXX0kkKKK0dc;,,,,,,codkKKXXXXXXXXXXXXXXXKKKKKKKKKKKKKKK")
    print("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXNNXXXXXXXXXXXXKK0KK0KXXXOOXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKdc;,,','',',lOXXXXXXXXXXXXXKOk0XKxc;,,;;;;,,,',ckKXXXXXXXXXXXXXXXXXXXXXXXXKKKKKK")
    print("XXXXXXXXXXXXXXXXXXXXXXXNNNXXXXXXXXXXXXXXXXXXXXXNXX0OO0XXKKKKKOOKXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKd;;;,,,,,,,,':kKXXXXXXXXXXXXKOO0K0d;,;;;,,,,,,,'';o0XXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
    print("XXXXXXXNNNNNNNNNNNNNNNNNXXXXXXXXXXXXXNNNXXXXXXXXNX0OO0XXXKKKK0OKXXXNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKkc;;;;,,;;,,,';kXXXXXXXXXXXXXK0kxOOl;,,,,;,,,,,,,,';xXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
    print("NNNNNNNNNNNNNNNNNNNNNNNNNXNNXXXK00KKXNXXXNNXXNNNNKKX00KKKKKOxoclldk0XNXXXXXXXXXXXXXXXXXXXXXXXXXXXKd;,;;;;,,,,,,,:kXXXXXXXXXXXXX0OO0KKx;,::;;,,,,,,',,:kXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
    print("NNNNNNNNNNNNNNNNNNNNNNNXNNKOdlcc:::coOXNXNNXXNNNXKKKKKXXXXk;,'','',;xXNXXXXXXXXXXXXXXXXXXXXXXXXXXN0c,;;;;;;,,,,;dKXXXXXXXXXXXXX0OOKXXOc,::,,,,,,,',,,dKXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
    print("NNNNNNNNNNNNNNNNNNNNNNNNN0o:,,;:c:::;:xXNNXNNNNNKKKKKNNXXXd,,,,;,,,'cKNXXXXXXXXXXXXXXXXXXXXXXXXXXXXx;,;,;;;;,,;dXXXXXXXXXXXXXXK000KKKKOo:,,,,,,'',,';kXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
    print("NNNNNNNNNNNNNNNNNNNNNNNNXx,',,;;;:;;;,c0NXXNNNNNKKXKKXXXXXx:::;;;;;,:kXNNNNNNNNNNNXXXXXXXXXXXXXXXXXKkkxo:;;;,,;oO00KXXXXXXXXXXK00OKKXXXKOl,,,'',,,,:xKXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
    print("NNNNNNNNNNNNNNNNNNNNNNNX0l,,,;;,;;,,;,lKNXNNNNNXKXXKKXXXXXOoc;;;;;;;;dXNNNNNNNNNNNNNNNNXXXXXXXXXXNXXNXXKd;;;;;,;:::clldk0XXXXXK000XXXXXXXKxc,,,,,,;o0KXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
    print("NNNNNNNNNNNNNNNNNNNNNNN0l,,,:c:;;;;::;lKNNNNNNNXXXKKXXXXXX0dc:;;,;::oKNXNNNNNNNNNNNNNNNXNXXNNXXXNXNXOddOd:;;;,;::,;:;;;;;oKNXX000KXXXXXKKKX0o::::;;,:lldxO0KXXXXXXXXXXXXXXXXXXXXXXXX")
    print("NNNNNNNNNNNNNNNNNNNNNNNX0xdlclc:;;;cold0NNXNNNXKXXKXNNNNXXXd;,;,,,,oKNXNNXKXXXNNNNNNNNNNNXNNNNXXX0kxl;:ll:;,;;:;,';:;:;;,;dXNXKK0KXXXXXXXXXXxc::;,,,,,,,,;::lox0XXXXXXXXXXXXXXXXXXXX")
    print("NNNNNNNNNNNNNNNNNNNNNNNNNNXOolc:::cd0KKXNNNNNNKKNX00OKNNNXN0c,,,,,l0NNNNNOk0kOXNNNNNNNNNNNNNXXNKxccl:,,;c:;:::;,;,;::::;;,cONKKKO0XXXKOOKXXXOo;,,,,,,,,,,,,,,,,:xXXXXXXXXXXXXXXXXXXX")
    print("NNNNNNNNNNNNNNNNNNNNNNNNNNXklc::;:o0NNNNNNNNNNXXNKkocxXXXXXk:;,,,:ONXNNNKxxdlkXNNNNNNNNNNNNNNXNOc:c:;,,,;;;;;,',;,;c:::;;;;xXKKK0XNKOo:l0XKd:;,,,,,,,,,,,,,,,,,,;dKXXXXXXXXXXXXXXXXX")
    print("NNNNNNNNNNNNNNNNNNNNNNNNNXOdcc:::cdKNNNNNNNNNXXXXKxc;cdkkkkl;;;;,;oOKXNXxllco0NNNNNNNNNNNNNNXNXxc::;'''','','',;;,,:::::;;;oKKKKKK0oc;,c0X0o:;,,,,,,,,,,,,,,,,,,,;xKXXXXXXXXXXXXXXXX")
    print("NNNNNNNNNNNNNNNNNXXXXKKKK0xol:::::lOXNNNNNNNXKKXX0dc;;:clllc:;,,;;:loodoc:cokXNNNNNNNNNNNNXNNNXxc:;,''',,,','',','',;:::;;,l0KXKOdl::;,ck0xc;,,,,,,,,,,,,,,,,,,,,,;xXXXXXXXXXXXXXXXX")
    print("NNNNNNNNNNNNNNNXKOxxxkkkxxxddoolllodkKKKKXNNX0KXKOxl:;:clooool::lllooolc::cxXNNNNNNNNNNNNNXNNNXkc:,',,',,,,'','',,,',;::;;,lOKX0o;;;:;,;ldc;,,,,,,,,,,,,,,,,,,,,,,,:kXXXXXXXXXXXXXXX")
    print("NNNNNNNNNNNNNNX0kxxxdxxxxxxdddddddddxkOOOOO0KXNX0kxl::coooddddolooddddxdlccxXNNNNNNNNNNNNNNNNNNOc:,',,,,'',,,,,,;;,',;::;;,ckKKd;,,;:;,;;:;,,,,;,,,,,,,,,,,,,,,,,,,,:ONXXXXXXXXXXXXX")
    print("NNNNNNNNNNNNNNKkkkxkkkkxdodooooooolloxxxxxkO0XNKOkdoc;:ododdddooodddddxxdold0NNNNNNNNNNNNNNNNNNkc;,,;;;;:;,;;;;;:;'',,::;;,ckXk:,,,,;;;;;,;;;;;;,,,,,,,,,,,',,,,,,,,,oKNXXXXXXXXXNNN")
    print("NNNNNNNNNNNNNX0OOkxxkOkxolllooooddolloooodxO0XX0kxool;;looodoodddddoddxdddolxXNNNNNNNNNNNNNNNNXd:;,;:::::;;;:;,:;'''',;;;,,c0Kl,,,,,,,,;;;;;;;;;,,,,,,,,,,,,,',,,,,,:kXNNXXXXXXXNNNN")
    print("NNNNNNNNNNNNNOdxkxxodkOkollllllooooollllodxOOKKOxllol;;looooooddxxxddxxoodolo0NNNNNNNNNNNNNNNNKo,,:xo;:::::;::::,',,',;;;,,c0Xkdoc;,,;;;;;;;;;;;,,,,,,,,,,,,,',,;;;;;xXNNNNNNNNNNNNN")
    print("NNNNNNNNNNNNXklcccc:lkOkdolooolooooooollodxkO0Odccllc;;lodddodddxxxddxoclddllxXNNNNNNNNNNNXNNNKo,,lOl,;;;;,,;;;,'','',,;,,,l0NKKNKo;;;;;;;;;;;;,,,,,,,,,,,,,,',:::::;c0NNNNNNNNNNNNN")
    print("NNNNNNNNNNNNKxlclc;:dOOxdllloollollllllllllodKO::ccc:,coddxxdxxxkxxdddc:cdollo0NNNNNNNNNNNNNNNNk;,ox:cxd:':ddoc,'',,,;;;,,,dXXKOkkxc;;;;;;;;;;;;;,,,,,,,,,,,,,,oo;;:;:kNNNNNNNNNNNNN")
    print("NNNNNNNNXXXN0olll::dO0Okdlooodollllllccll:::l0k::cc:,;oddxxddxxdxxxddddolooolxXNNNNNNNNNNNNNNNNO:,ll;d0d;';oxdc,',;;;;;;,;cONXOl;ldc;;;;;;;;;;;;;;;,,,,,,,,,,,,x0c,;;;oKNXNNNNNNNNNN")
    print("NNNNNNXK0OxOOlclc:ck000ko:cldxxdodollccoo:::lkklclolcoddxxxddxxxxdddddOXKxoookNNNNNNNNNNNNNNNXNKo,,;okOo,,';dxc,,;;;;;,;okKXNKd;:xd:::;;;;;;;;;;;;,,,,,,,,;,,,,oKd;;;;c0NXNNNNNNNNNN")
    print("XNNNNXK00x:ldc::cldO00Oo::odxxxxxdoooodko;;:lk0Odd0OdxxxxxxdxxxxxxddxxOXNX0O0XNNNNNNNNNNNNNNNNNNk;':x00kc;;col;,;;;;,,,lKNXXX0xcckd;;;;;;;;;;;;;;,,,,,,,,,,,,,,l0x;;;;cxOOXNNXXXXNNN")
    print("OOKNNNKxl::oo:;;lxO000Oxdxkkkkkkkkkkkxkko;;;:ok0kOKOxxxxxxxdxxxxxxddxxOXNNNNNNNNNNNNNNNNNNNNNNXXKd;,l00kollc:;;;;,,,'''cdkKX0kllolc:;;;;;;;;;;;;;,,,,,,,,,,,,,,:xo;;;;;:;:dO0OkkKNNN")
    print(":;cdkOklcclxo:;:xOO000OOOOOkkkkkxkkkkxxko;,;;cxkOKKOxxxxxkxdxxxkkxxxxx0NNNNNNNNNNNNNNNNNNNNNNNXXKkdlldl;;,,,,,,,,'''''',:oxOOxodd:;:;;;;;;;;;;;;;,,,,,,,,,,,,,,,cl:;;;;;,;;;:oxOKXNN")
    print(",,,;loc:;;odc:;ckOO0000OOOOOkkkkkkkkxxkko;,;;:oOK0kxxxxxxkxdxxkkkxxdxkOKXXNNXNNNNNNNNNNNNNNNNN0kkxdoc;;;;;,,,'',',,,;:::cc:okxool::;;;;;;;;;;;;;;;,,,,,,,,,,,,,,;oc;;;;;,;:::lokKXXX")
    print("cc::::llccloc;;cdk00000OOOOOkkkkxkkkkkkkd:,;;:lkKkdxxxxxxxddxkxkxxxdxkkdldOXXXXXXXXXXXXNNNNNXXOdolc:;;,,,,,'','',,';cooc:::dOdc:;:;,,;;;;;;;;;;;;;;;,,,,,,,,,,,,;::;;;:;,,,,;:coxkxo")
    print("dxdddxxxxdxoc;;ldk00000000OOOOOkkkOOkkkkkd:;;;lk0kdddxxxxxxxxxxxxxxdxkkxc;ckXXXXXXXXXXXXXXXXXXKo::::;;,,,,,,,,''',,,;::,;;:okl,,;;;,;;;;;;;;;;;;;;;;;,,,,,,,,,,,,,;:;:;;,,,,;::;;::;")
    print("ccodxoccccoo:;:oxO00000000OOOOOOOkOOkkkkkOl,;;ldoodddxxxxkkkxxxxxxddxxkkl;;cokOOOKXXKKXXXXXXX0l:loollcccccccc:::;;,,,::,;:,:lc;;::;,;;;;;,,,,,,,,,,,,,,,,,,,,,,;:ccc:::::;,;;;,,,;;,")
    print(",,:cll:,,,:l:;;oO0000000000O00OOOOOOkxxkxkl;,;::clodxxxxxkkxxkxxxxddddxxl,,;:clllok0KKKXXXXX0c;oxdddddooddoodooollc;':l;,;,:llc::c:;;,,,,,,,,,,',,,,,,,,,,,,,,;cllccccccccc::;:cllcc")
    print(",,,:llc:c;:lc;;l0K000000000000000000Oxolccc;,;::cc:ldxkkxkxodkxkxxdddlccc:;::cllccldxO0XXKK0o;ldxddxddoodoloddooool:,;lc:cloddoccccc;',,,,,,,,,,,,,,,,,,,,,,,',ll:llcccodkdooolooood")
    print("ollodxxxkdddl::dKK0OOkxxxxxddoooooool:;,,:oc;:lxd:,,:cooddlcoxoooolc:;,cxxdxxkkkkkkxxk0XXK00doxdddxddol:;coooooooolc,;okOO0OOOkoccc;,,,,,,,,,,,,,,,,,,,,,,,,,',;::cc:::oxxxkkdodoodd")
    print("xxxxxxxxxkkkoc:oOxolc:;;;::;;;;::::cc:;;;col;lxko;,,,,,,;,,,,;,,,;,,,,,:odxxxxO0000KKXXNNNNXK0kdddddolc;,lxddoolllll;,cxxxOkxOxlcc:;,,,,,,,,,,,,,,,,,,,,,,,,,,',;;::;;;lolclddlolcoo")
    print("xxkkxdxxxxkkdoc:odlc::::ccc:;;:clllllcc:::ccclkOd:,,,,,,,,,,,,,,,,,,,;;cdxkkk0KKXNNNNNNNNNNNX0ddddoool:;;oxxxddoolol;'cxxdxxxxdlllc;,,,,,,,,,,,,,,,,,,,,,,,,,,'',;::;;;:llc;cllc:::c")
    print("kkkkxxkOkxkkdoc;:lcccllclcc:;;:cclloooll::llclx0x:,,,,,,,,,,,,,,,,,,;,;oOO0KKXNNNNNNXXXXNXXNXkoddoollc::oxkxxxdoooooc;:oodxdolccc:;;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;;:cllcoo::ccc::c;:")
    print("kOOkkOOOOkkxdolc::::llllcc::;,;clcloooolcldocdkkxc,;,,,,,,,,;,,,,,,,;;:kXXNNNNNNNNXXXXXXXXXXKxoooolllccx00kxxxdoooddo:;dkxxolllcc:::;,,,,,,,,,,,,,,,,,,,,,,,,,,,;cloodxolc;;,;;,;,,,")
    print("llodxkOkkkkdodccc::clllccc:::;;llccodddollloxO0Okc;;,,,,,,,cl;,,,,,,;;l0NNNNNNNNNXXXXXNNNXXN0dooolllclxKNKkxddddooddd:,oxdoccoddooxdl;,,,,,,,,,,,,,,,,,,,,,,,,,,lxxkxddolc;;,;,,;,,,")
    print(":ccoodddxxdclo;;c::cllllc::cdo:cllloxxddoodkkkO0Ol;;;,,,,,,dd;,,,,,,;;dKNNNNNNNXXXXXNXXXNNNXOoollllllxKNXKkxddddodxl:,;dxdo:cdkxxxkd:,,,,,,,,,,,,,,,,,,,,,,,,,',lxxxxddxxdddc;,,,,,,")
    print("dddxkxddxo:;;,,;c:cclllc:::d0kl:llodxxxxk0K000KXKo;;;;,,,,;kx;,,,,,,;;xXNNNXXXXKKKXXXXXXNNNXkollllllo0XXX0kxddooodxkddxkxkkddxkkxkOx;,,,,,,,,,,',;,,,,,,,,,,,,,;odddxddxxxxo:;,,,,,,")
    print("kkkOOOkkxc',;,,;cc:ccccc::lxOkoccloxkxxxOXXXXXNNXd:;;;,,,,c0Kl,,,,,,;cONNXXXXK00KXXKXNNNNNNKdllllllokXNNN0kddollodkKXXKKK0OOkkxxxxkkc,,,,,,,,,,'cl;,,,,,,,,,,,';oddddoclooddl::;;,,,")
    print("kxxxkxxkl,;;;,;:cc::cccc:lk000dcclodxxxkKNNNNNNNXx:;;,,,,;dXXd;,,,,,;lONXXXKK000KKXXXNNNNXKkllllllld0NNNXOxdolllod0XXXXXNXXK0koodkOOo;,,,,,,,,,'cxc,,,,,,,,,,,,;loolll:looodxdddc;,;")
    print("c:;coool;,:;,;::c:;:::cccxXXKKxcclldxxx0NNNNNNNNNKx:;;;;:oKNNOc;;,;,cxKXXXXX00KKKKXXNNNNNKOxloooolldKXXNXOxdolcloxKNNNNNNNNXXK000OOOkc,,,,,,,,',cxo;,,,,,,,,,,,;lllcclcloccoooxxooll")
    print("ooc::ldl,;;;;;:::;;;::c:o0XXXXkcccldxxkKNNNNNXNNXXOl;;;:cONNNKo:;;;;dKXXXXXKKKKKXXXXNNNNNX0koddddolokKXXKkddlccloxXNNNNNNNNNNNXXXK0OOo;,,,,,,,',cxd:,,,,,,,,,,,;llc::coddooooodddxxd")
    print("xkOkkO0x:;:;::;;;::::::ckXNNNNOlcllodxOXNNNNNNNNNN0l::::dXNNNXxc;;;cxKXXXKKKKKXXNNXXNNNNNNNXOdxxxdooxOXXXOdolc:clxXNNNXNNXNNNXXXXXXXKk:,,,,,,,,,cddl,,,,,,,,,,,lxxdoooxxdoddxkkkxdoo")
    print("KKXXXXXOolddxkd::cc:::;oKNNNNNKdclloxkKNNNNNNNNNNXklcccoONNNNNOl:::lkKXXKKKKKXNNNNNNNNNNNNNNXOxxxxddxk0XXKkdolcclxKNNNNXXXXXXXXXXXXXXOc,;,,,,,,,cool;,,,,,,,,,;okkkkkxdllcldxdxdollo")
    print("KXXXXKKKO0XXXXOdoool::ckNNNNNNXklcloxxOXNNNNNNNNNKdcccclONNNNXxc::clkKKKKK0KXXXNNNNNNNNNNNNNNNKkxxxxdxkKXXOxdlcloxKNXNNNNNNNNNNNXXXXXKd:;;;,',',lxxo:,,,,,,,,,,oxdodddl:cclolloclodd")
    print("XXXXX0KXXXNNNXOxdolc:cxKNNNNNNXklccllokKNNNNNNNNN0o::::cxXNNN0o::::lxKKKK0KXXNNNNNNNNNNNNNNNNNX0kkxxxddOXXOxdollod0NNNNNNNNNNNNNNXXKXNO:,,,'',';xKK0x:,,,;;;,,,cdooodxdodoooloddxxdo")
    print("XXXXNXXNNNNNNXOxolccclONNNNXXNXdcccllld0NNNNNNNNNKo:::::dKXXXx:;;::oOXK0O0XXXXXNNNNNNNNNNNNNNNNX0kkkkxdxKXOxdolcld0NNNNNNNNNNNNNNNNXXX0c,,,'','c0XXXXd,,,,,,,,';looooddddoloodxxxxxx")
    print("NNNNNNNNNNNNNKkdolllcoKNNXNNXNKdccclold0NNNNNNNNNXxc::::o0XX0l::;:ckKK0kk0XXXXXXNNNNNNNNNNNNNNNNX0kkkxdd0Xkddolcld0NNNNNNNNNNNNNNNXXNKo,,,,,,,';OXXXXx;',,,,,,,;dkxdoddoolccoxxooddx")
    print("NNNXXXNNNNNNX0kkolcccxXNNNNNNNXxccclllxKNNNNNNNNNNOl::::oKNNk:;::coOK0kdkKXXXXXXXNNNNNNNNNNNNNNNNX0kxxxdOKkddolcldKNNNNNNNNNNNNNNNNXX0c,,,,,',',xXXXXO:',,,,,',;dOOxooooooddddoodddd")
    print("K0kxkKXXNNNNKkkkoccccdKNNNNNNNXxccccllxXNNNNNNNNNNKoc::;dXNNO:;;:cxKK0OO0KXXXXXXXNNNNNNNNNNNNNNNXXXOkkxdxOkxdolclxKNNNNNNNNNNNNNNNXNNXk:,,,,',',oKXXX0c',,,,',,,lO0OOkxxdxxxoooooooo")
    print("KKKKXXNXXXNXkdkkdcccco0NNNNNNN0xlccclod0NXXNNNNNNNKl,,,,lkkOx:,,,:xK0KKKKXXXXXXXXNNNNNNNNNNNNNNNNNNKkxxxxkxxdollokKXXNNNNNNNNNNNNXNNXNKl,,,,,,,'cO00K0l',,,,,,,'ckOO0Okollodxddlcclo")
    print("XNNNNNNNXNNKooxxdllcclkXNNNNNXkllolclolxXXXNNNNNXXKx;,,;xKKKk:',,lkO0KXXXXXXXXNNNNNNNXNNNNNNNNNNNNNKOxxxdoxxdoolok0KXXXNNNNNNNXXXXNNXNXo,,,,,,,':k0KXKo,,,,,,,,':kKK0koodooxxdddoodo")
    print("XKKXXXXNNNNOllxxdolcccxXNNNNNXdcclollo:oKNNNXXXKO0X0c,,;dKXXk:,,;dOk0XXXXKKKXXXXNXNNXXXNNXXNNNNNNNXKOxxdlcxxdooodOKOOKXXNNNNNNXXXXXXXNXx;',,,,,',dKKXKo,',,,,,,';dKK0OOOOOOOO0Okkkxo")
    print("XXXXNNNNNNXxcodddolccco0NNNNNXd:::llooccONXXK00OkkKOc,,,cOX0l;,,;lxOKXXKK0KKXXXXXNNXXXNNNXXNNNNNNNXKxcloloxxxoood0XKK0KXNNNNNNNNNXXXXXN0l,,,,,'',o00KXd,',,,,,,',o0KKXXXK0000K0Okxxd")
    print("NNNNNNNNNNKdcloolcc::clONNNNNKo::ccclllokXNNXXXXXX0o;,,,:ONOc,,,,;lxO00000KKKXXXXXXNNXXXXXXNNNNNNNX0dldddxkxdollxKNNXXKXXNNNXNNNNNXXXXNKd:,,,,'''c0XKKo,,,,,,,,,,lKXKKKKKXKK000OOkxx")
    print("NNNNNNNNNNXxcllcc:::::lKNNNNNKd::;:::;;:xXNNNNNXKOoc:,,';xXk;,,,,,:d000KXXKXXXXXXXXXXXXXXXXNNNNNNX0xxddooodddollkXNNNX000KXXXXNNXXXXXXNKx:,,,,,,';kXXKl',,,,,,,,'c0XX0kkkOOOkkxkkdod")
    print("NNNNNNNNNNNKklllol:;;;xXNNNNNXx:;;:c:::ckXNNNNX0kxxo;,,',o0o,,,,,,,;oOKXXXXXNNXXNXXXXNNNXXXNNXXX0kdooccclodolc:cxXNNNXXKKXNNXXNNXXXXXXX0c,,,'',,',dXXKo',,,,,,,,':ONXKKK00K0kkkkxddx")
    print("NNNNNNNNNXN0dlccc:;::cONNXNNNNOc:c::::;:oOXNNXK0OOxc,''',:ll:;,,,,,,;cd0XXXKKKKXXNNXNNNNNXKKKK0xoollokO0KXkc::::xXNNNNNXXXXXXXXXXXKKXXXO:','',',',dXXKo',,,,,,,,':OXXKXXXXKKKKK0OOkk")
    print("NNNNNNNNNNN0xoc:;;;;:xXNNNNNNNKo::;,,,,',;d0XKdc:;;:col;,,';lolccc;,;,;o0XXKXXXXXXXXXNXXXXK0xoollc::lxxxxkxoc:;;l0NNNXNXXXXXXXXNNXXXXXXKo,,''','''lKXKo,'',,,',,';kXXXXNXXXKKKKKK0OO")
    print("NNNNNNNNNXXXx;,,'''':OXXXXXXXXKl,,,,',,',,,ckK0kxxk0KXKd;',,;cldOOd:,,,,cdk0KXKKKXXXXXXXXXNX0xdddoolc:cc::xxc;;ccoOXNXXNXXXXXXXNNNXXXXK0x:,,,,';oxkKXKd,',,,'',,':kXKKKXXXXXKKXXXK00")
    print("NNNNNNNNNNNKl,,,'''',:ldOKXNXXXOl;,,,,,,,,,:kKKXXKKK000kc,',,,,,ck0kdl::;,;:lx0KXXNNNNNXNXXXNNNNNNNXKKKK0OKKd:;cc;cd0XXNXXNXXXXXXNXK0Od:;,,,,,',dKXXXXk;',,'''',':OK00KXXXXXXXXXXXKK")
    print("NNNNNNNNNNXXx:,,,,,,,,,,:kNXXXXNX0xc,,,,,,,;lxkO00KKK0kxdl;,,,,,,:okOOOxc,,,,;lxKXNNXXKK000XNNNNNNNNNNNNXNNX0o:cc:,;ckXNXXNXXXXXXXKOko;,,,,,',,';xXXXXk:;,,,,'',':OXKKXXXXXXXKKKKKK0")
    print("NNNNNNNXXXXXX0dc,,,,,,,,;o0XXXXNXXX0d:,,,,,,,,:dxkO00Ododoccc;,,,,,;cokxxxl;,,,;cx0XK000KK0KKXXNNNNNNNNNXNNXXOlcl:,,,;cx0KKXXK0kkkxo:,,,co:'',,,'l0XXKOxko;',''',oKXXXKKKKKK0KXXKK00")
    print("NNNNNNXXXXX0O0Kkc,,,,;;;,;lOKKXKKXXXKd;,,,,,,,,cdxkkkkddoldOOo;,,,',,:x0KX0o,,,,;;cxOKK0KK00KXXXXXXNNNNXNNKOkxlcc:,',,,;oO000kc,,,,,',,':kx;',,,';lkKK000x;','',,oKXXXKOkkOOO0XKK0O0")

def blank_banshee_1_art():
    print("        'kKKKKK0o.  ;Ok,        .lKO,    ;0Kc   'xO, ;Ok'  .dKk;     .dKKKKKK0x'     :00:    ,kKo.  .d0:  ,xKNNKo.  ;Ok'   ,OO, ;0KKKKKKO; :0KKKKKKO;  ")
    print("        lWWNNNWMWl .dWk.        :XMX;   .xMMx.  lNO..xWk. ,OW0;      :XWNNNWMMMd.   ,0MWl   .oWMO'  ;XK, cXWK0XMWl .dWk.  .dWO..xMWNNNNNO'.xMWNNNNNk'  ")
    print("       .kWx,,,oXWl '0Wo.       'OMMX;   ,KMMO. .kWo ,0Nc.cXNx.      .dWO;,,cxKMx.  .xWMNc   .OMMK; .dWx.;XKc..:KWd.'0Nl.  '0Wo ,KNo,,,,,' ,KNo,,,,,..  ")
    print("       :XK;   :XK, lNK,       .dNNWK;  .oWWWK, ;XK; lW0:dNXc.     . ,0Nc   ,dKXc  .lNNWNc . :XWWNc '0Nc.xMx.  .ld,.lN0,   cNK; oWO'    . .oWO'         ")
    print(" .... .dWKl::lKXl..kMx. ......cN0kNK,  .ONk0X:.dWk..kMK0W0;.........lNXo::lOWNd. .;KKkKX:  .xWO0Wo.cN0''0MXd:'. . .kMKollo0Mk..OM0lccc:. 'OM0lccc;.....")
    print(" .... ,0MMMMMMWo. ;KNc.......,0NloN0, .:X0ckWl,0Nl.:XMMMWd........ .kMMMMMMWWx...'kWdcXX:..,0XldMd'xWd..kWMMWXk;..:XMMMMMMMNl.:XMMMMMMO' cXMMMMMMO'....")
    print(" .....lNXOkk0NMk..dWO'.......kWx'oW0, .xWx'dMxlN0,.dWMWWMO'........:XNOkkONMM0,..oN0,cNX:..lNO'lWklKX:..'oOXWMM0,.dWXkxxkXM0,.xWXOOOOOc..xMXOOOOOc.....")
    print(" .....kWd...'kMO''0Wd.......oNK;.xMO, ;0Nc.oW00Wx.,0WOlOMX:........dWk'...dWMK;.cXXc.lWK:.'kWd.cXK0Nk'.....,lKMK,'0Wo...'OWd.,0No.......;0No...........")
    print(" ....:KXc...,0Wd.cNX:......:KNo..kMO'.oNO,.cNWWXc.lNK;.dWWd.......,0No...'kMMk',0Wx..oWK;.:XK:.;KWWWl'dOc....xMk'lNK:...cNX:.oNK;.......oW0;...........")
    print(" ....dWKc,;cOWK;.kM0c;::;.,OWk'.'kMO''OWd..;KMMO'.kMk'.cXM0,......lNXl;;:xNXOc.xW0;..xMK;.xWk'.,OMMK;;KMO;';dNX:'kMk'...xMO''kM0c;:::;.'OM0c;:::;......")
    print(" ...,0MWNNNWMKc.:KMWWWWWO:dWK:..,OMO':XX:..,0MWo.:KNl..,0MXc.....'kMWNNNWMXl'.lNNl..'kM0,,0Nl..'kMMx.,OMWXKNWKc.:KNl...;KWo.:XMWWWWWWk':XMWWWWWWk'.....")
    print(" ...:0XXXXK0d;..lKXXXXX0c:OKo...,kXd'lKx'..'dXO;.lKk,..'dXKo.....;OXXXXK0x:..,kXd'..'dXk,c0k;...oK0c..:kKXX0d;..lKk;...lKO;.oKXXXXXXKl.oKXXXXXXKl......")
    print(" ...',,,,,,'....',,,,,,,.',,'....,,'.','....','..','....',,'.....',,,,,,'....',,'....','.','....',,'....,;,'....','....',,..',,,,,,,,'.',,,,,,,,'......")
    print(" ......................................................................................................................................................")
    print(" ....................................................''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''")
    print(" ''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''")
    print(" ''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''")
    print(" ''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''',''''''''''''''''''''''''''''''''''''''''''''''''''''")
    print(" ,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,:llc:;;;;;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,")
    print(" ,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,:oxxddolc:::;;;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,")
    print(" ,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,:oolc::::::;;,,,,,:odxxxxxxdollc:::;;;;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,")
    print(" ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:ldkkkxdollccccc:;;:odxxxxxxxxxxddolcc::::;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;")
    print(" ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,''........'',;;;;;:okkkkkkkkkxdolcccccloddxxxxxxxxxxxxxdoc::::::;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;")
    print(" ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,'''............',;:okkkkkkkkkkkkkxdollccclloddxxxxxxxxxxdlc::::::;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;")
    print(" ::::::::::::::::::::::::::::::;;,,,,,,,,,''',;::::::;,'''''''...........,lxkkkkkkkkkkkkkkkkxolclcclldxxxxxxxxdlc::::::::::::::::::::::::::::::::::::::")
    print(" ::::::::::::::::::::::::::::::,'..............',;::;,'''''''''''..........',;ldkkkkkkkkkkkkxollllllodxxxxxxxdlc:::::::::::::::::::::::::::::::::::::::")
    print(" :::::::::::::::::::::::::::::;,''''..............',,'''''''''''''''............,lxkkkkkkkkxollllllodxxxxxxxdlc::::::::::::::::::::::::::::::::::::::::")
    print(" cccccccccccccccccccccccccccc:,'''''''''...............'''''''''''''''...........ckkkkkkkkxollllllodxxxxxxxdoc::::ccccccccccccccccccccccccccccccccccccc")
    print(" ccccccccccccccccccccccccccc:;'''''''''''''...............'''''''''''...........ckkkkkkkkkolllollloddxxxxxdoc::::cccccccccccccccccccccccccccccccccccccc")
    print(" ccccccccccccccccccccccccccc;'''''''''''''''''.............''''''''''..........:xkkkkkkkkolllxOkxdolooddxdoc::::ccccccccccccccccccccccccccccccccccccccc")
    print(" cccccccccccccccccccccccccc:,'''''''''''''''''.............'''''''''..........;xkkkkkkkkdlllxOOOOOkxdollooccccccccccccccccccccccccccccccccccccccccccccc")
    print(" lllllllllllllllllllllllllc,''''''''''''''''''............'''''''''..........,codxkkkkkdlllxOOOOOOOOOOkdollllllllllllllllllllllllllllllllllllllllllllll")
    print(" lllllllllllllllllllllllll;''''''''''''''''''............'''''''''.........';cllloodxkdlllxOOOOOOOOOOOOOOkxdollllllllllllllllllllllllllllllllllllllllll")
    print(" llllllllllllllllllllllllc,'''''''''''''''''............'''''''''.........'collllllloooloxOOOOOOOOOOOOOOOOOOkolllllllllllllllllllllllllllllllllllllllll")
    print(" oooooooooooooooooooooooolc:,''''''''''''''......';;,'''''''''''.........'coooooooooooooxOOOOOOOOOOOOOOOOOOOxollllooooooooooooooooooooooooooooooooooooo")
    print(" ooooooooooooooooooooooooooolc:,'''''''''''.....';:::;;,''''''''.....,;ccloooooooooooooxOOOOOOOOOOOOOOOOOOOxolllloooooooooooooooooooooooooooooooooooooo")
    print(" oooooooooooooooooooooooooooooolc;,'''''''......;:::::::;;,'''''''''',;:cooooooooooooodkOOOOOOOOOOOOOOOO0Oxollllooooooooooooooooooooooooooooooooooooooo")
    print(" ddddddddddddddddddddddddddddddddolc;,'''......,:::::::::::;;,''''''''''',:llodddddddddxkkOOOOOOOOO0OOO0Oxolllloddddddddddddddddddddddddddddddddddddddd")
    print(" ddddddddddddddddddddddddddddddddddddlc;,',,;;;:::::::::::::::;;,''''''''',:loddddddddddddxkkOOOOOOOOOOOxollllodddddddddddddddddddddddddddddddddddddddd")
    print(" dddddddddddddddddddddddddddddddddddddddoddddoc::::::::::::::::::,''''''',:odddddddddddddxdooodxOOOOOOOxolllloddddddddddddddddddddddddddddddddddddddddd")
    print(" xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxoc::::::::::::::::::;,''''''';oxxxxxxxxxxxxxkOOxdollodxkOOxoloooddxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx")
    print(" xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxdc::::::::::::::::::;,''''''';colcccodxxxxxxkO0000Okdolloddlllloddxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx")
    print(" xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxoc:::::::::::::::::;,''''''''','....';codxxkO00000000Okdolllllllllodxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx")
    print(" kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxdoc::::::::::::::;,''',,,''...........';cok000000000000Okxolllllllloxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk")
    print(" kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxdoc:::::::::::,''',;;;;;,''...........';lxO000000000000Okxollllodkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk")
    print(" kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxdlc:::::::,''',,;;;;;;;;,'''..........';lxO00000000000kolllodkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk")
    print(" OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkkOkxdlc:::;'',,,;;;;;;;;;;;;;,''..........'ck000000000kollloxkOkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO")
    print(" OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOxdlccloo:;;;;;;;;;;;;;;;;;,''.......,d000000000kollloxOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO")
    print(" OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkOOOo;;;;;;;;;;;;;;;;;;;;,'.....,d000000000kollloxOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO")
    print(" cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccll:;;;;;;;;;;;;;;;;;;;,'.....,d000000000kolllc:cccccccccccccccccccccccccccccccccccccccccccc")
    print("                                                            .,;;;;;;;;;;;;;;;;;;;;'......,oO0000000kolll:.                                             ")
    print("                                                            ..,;;;;;;;;;;;;;;;;;;'..''.....,cdO000koc:'.                                               ")
    print("                                                               ..,;;;;;;;;;;;;;;''.'',''......,cdd:,'..                                                ")
    print("                                                                  .',;;;;;;;;;;''.'',,,,,''...............                                             ")
    print("                                                                    ..';;;;;;;''.'',,,,,,,,,''..............                                           ")
    print("                                                                       ..,;;,'...',,,,,,,,,,,,,''...........                                           ")
    print("                                                                          ...   .',,,,,,,,,,,,,,,'''.......                                            ")
    print("                                                                               .',,,,,,,,,,,,,,,,,,''.....                                             ")
    print("                                                                              .',,,,,,,,,,,,,,,,,,''.....                                              ")
    print("                                                                              .'',,,,,,,,,,,,,,,,''.....                                               ")
    print("                                                                                ..',,,,,,,,,,,,,''.....                                                ")
    print("                                                                                   ..',,,,,,,,,'.....                                                  ")
    print("                                                                                      ..',,,,,'....                                                    ")
    print("                                                                                        ..'','...                                                      ")
    print("                                                                                           ...                                                         ")
    print("                                                                                                                                                       ")

def blank_banshee_0_art():
    print("''''''''',,','''''''''''''''''''',,'''''',,''''',,''',''''''''''''''''',,'''''''''''',,''''''''''''''''''''''''''''',,'''''''''',,,,,'''''',,,,,,,,'''")
    print("''''''',;::::;;,''',;;,''''''''',;;,'',',;;,''',;:,',;;,''',;:;,'''',;::::::;,'''''',;:,,''',;:;,'',;:;,'',:cl:,',',;;,''',;;,',;:::::::;,,;:::::::,''")
    print(",,,,,,'c0XXXXXKk:',l00l',,,,,,';xX0l',,,oKXd,,'cO0l,lK0c',:kX0l,,,,':kXXXXXXKOc,,,',oKKo,','c0Xx;,,:kKo,,lOXWWXk:',lK0c','l00l,oKXXXXXXKl,oKXXXXXX0l,,")
    print(",,,,,,,xWWWWWWMWx,;kM0:',,,,,,,oNMNo',';OMMO;',dW0:;OMO:,lKWKl,,,,,,oNWWWWWMMMk;','cKMWd,,,,xWMKc,,oXXl,dNWXKNMWx,;kM0:',,kW0:;OMWWWWNW0c;OMWWWWWW0c',")
    print(",,,,,':0WOlccxNWx,cKWx,,,,,,,'cKMMXl','lXMM0:':0Wx,cKWd;dXWO:,,,,,';kW0lccdOXMk;,,:OWMWd,,':0MMXl';kWO;oXXd;;oXMk,cKWd,,'cKWx,lXNkccccc:,lXNxccccc:,,,")
    print(",,,,,,oNXl',,oNXl,dWXl',,,,,,;kWWWXl',,xWWWXl'oXXl,xWKokWXd;,,,,,,'cKNd,,'lkXNo,,,xNWWNd,,,oNWWNo'cKNd;OMO;,,:dkl,dWKc',,dNXl,xWKc',',,,,xW0c',,,,,,,,")
    print(",,,,,;kWXdooxXNd,:OMO;,,,,,,,dNKONXl,,:0N0KNo,kWO;:0MXKWKl,,,,,,,,,dWNxoodKWNk;,,lXXOXNo,,;OW0KWx,dNKccKMNko:,',':0MXkddxKMO;:0MKdodol;':0MKdodol;,,,,")
    print(",,,,'cKMMMMMMWx;'lXNd,,,,,,,cKNdxWKc,,oNKoOWdcKNd,oNMMMMk,,,,,,,,':0MMMMMMMWO:,,:0WkdXNo,,cKNdkMk:OWk,:OMMMWXOl,,oXMMMMMMMNd,oNMMMMMMKc'oNMMMMMM0:,,,,")
    print(",,,,,dWN0OOKWMO:,kWKc,,,,,,:OWO:xWKc';kWk:kMkxNKc;kMMWWM0:',,,,,,,oXNKOO0NMMKc';xWKcoNXl',xW0:dWOdXXl,,:x0NWMMKc,kWNOOOOXMKc;kWN00000d,;kMN00000d,,,,,")
    print(",,,,:OWk;,,:0M0:cKWk;,,,,,,xWXl;kMKc'cKNo,xWKKWk;cKW0d0MNo,,,,,,,;kW0:,,;kWMXl,oNNo,dWXl':0Wx,oNXKW0:,;,,;:dKMXccKWx,,,:0Wk,cKWx,,,,,,,cKWd,,,,,,,,,,,")
    print(",,,,lXNo,,,cKWk;dNXl,,,,,,lXNx,;OM0:,xW0c'oNWWNo,dNXl,kWWk;,,,,,,cKWx,,,:OMMO:cKWk;,xWXl'oXXl'lXWWWd:k0o,,,;OMO:dNXl,,,oNXo,dWKc,,,,,,,xWKc,,,,,,,,,,,")
    print(",,,;kWKocco0WKc;OMKollll;:0WO:,:0M0::0Wx;,lXMM0:;OMO;,oNM0c,,,,,,dNXdcclOWX0o;kWKc,;kMKc,kWO:':0MMKclXM0c:ckNXl:OMO:,,;OM0::0MKollllc;:0M0ollllc;,,,,,")
    print(",,,cKMWNNNWMXo,lXMWWWWW0lxWXl,,:0M0:lXXl,,c0MWx,lXNd,,cKMNo,,,,,:OMWWNNWMNd;;dNNd,,;OMKccKNd,,;OMMO;:0MWNXNWXo,lXNd,,,lKWx,lXMWWWWWWO:lXMWWWWWWO:,,,,,")
    print(",,,lKXXXXXKkc,,dKXXXXXKol0Xd;,,:OXk:dXk:,,;kX0c,dXOc,,;xXXd;,,,,c0XXXXXKkl,':OXk;,,;kXO:lKOc,,;dXKo,,lOXNX0xc,,dXOc,,,oK0c,dXXXXXXXXd;dXXXXXXXXd,,,,,,")
    print(",,,;::::::;,,,,;:::::::;;::;,,,;::;;::;,,,,;::;,;::;,,,;:::,,,,,;::::::;,,,,;::;,,,;:::;;::;,,,;::;,,,;:c:;,,,,;::;,,,;::;,;::::::::;,:::::::::;,,,,,,")
    print(",,,,,,,;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,")
    print(",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,")
    print(";;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,,,,,,,,,,,,,,,,,,,,,,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;")
    print(";;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,,,,;:clodxkkkkxxdooll:;,,,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;")
    print(";;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,;:ldkOKKXXXNNNNNNNNNNXKOdl:;,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;")
    print(";;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,,;lxO00KKXXXNNNNNNNNNNNNNNNNX0xc;,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;")
    print(";;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,;okO00KKXXXNNNNNNNNNNNNNNNNNNNNXx:,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;")
    print(";;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,;okO00KKXXXXNNNNNNNNNNNNWWNNNNNNNN0l;,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;")
    print(";;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,;lkOO00KKXXXNNNNNNNNNNNWWWWWWNNNNNNNXkc,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;")
    print(";;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,cxOO00KKXXXXNNNNNNNNNNWWWWWWWNNNNNNNNN0o;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;")
    print(";;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,;okO00KKXXXXNNNNNNNNNNWWWWWWWWNNNNNNNNXXXkc;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;")
    print(";;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;cxOO0KKKXXXXNNNNNNNNNNWWWWWWWWNNNNNNNNXXXX0d:;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;")
    print(";;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:okO00KKKXXXXNNNNNNNNNNWWWWWWWWNNNNNNNNXXXXXKOl;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;")
    print("::::::::::::::::::::::::::::::::::::::;;;;;cxOO0KKKKXXXXNNNNNNNNNNWWWWWWWWNNNNNNNNXXXXXKK0xc;;;;;;::::::::::::::::::::::::::::::::::::::::::::::::::::")
    print(":::::::::::::::::::::::::::::::::::::::;;;;okO00KKKKXXXXNNNNNNNNNNNWWWN0xkKNNNNNNNXXXXXKKK0ko:;;;:::::::::::::::::::::::::::::::::::::::::::::::::::::")
    print(":::::::::::::::::::::::::::::::::::::::;;,;okO000KKKXXXXNNNNNNNNWWN0xl;..,clox0XNNXXXXXKKK00Oxc;;;::::::::::::::::::::::::::::::::::::::::::::::::::::")
    print(":::::::::::::::::::::::::::::::::::::::;;,..cxO00KKKXXXXNNNNNX0kdc;,,;ldOKK0Okk0XNXXXXXKKK0000koc:;;::::::::::::::::::::::::::::::::::::::::::::::::::")
    print(":::::::::::::::::::::::::::::::::::::::;;;;,'',:d0KKXXXXXNKd:;;;:ldk0XNNNNNNNNNNXXXXXXXKKK000OOOkdoc:;;;;:::::::::::::::::::::::::::::::::::::::::::::")
    print("::::::::::::::::::::::::::::::::::::::::;;:lolc;cxO0KKKXXXKxdkO00KKKKXXNNNXXXXXXXXXXXXXKKK000OOO0OOkxdddoc::::::::::::::::::::::::::::::::::::::::::::")
    print(":::::::::::::::::::::::::::::::::::::::::;;:ldddoodxO0KKKKKK000000OkkkkOOO0KXNNNNNXXXXXKKK000OO00KKKKKK0kdl:;:::::::::::::::::::::::::::::::::::::::::")
    print(":::::::::::::::::::::::::::::::::::::::::;;;:c:::cclox0XXXKK00K00kl;,;;;;,;;l0NNNNNNXXXKKK000OOO0KKKKK0Oxol:;:::::::::::::::::::::::::::::::::::::::::")
    print("::::::::::::::::::::::::::::::::::::::::::;'.,,,,;;clo0NNNNXXXXXKkl;;;:clodxOXNWNNNNXXXKK0000OOO0KKKK0Okxol:;;::::::::::::::::::::::::::::::::::::::::")
    print("::::::::::::::::::::::::::::::::::::::::::;;:ldxkOOOkOKNNWNNNNNXK0OkO0KXNNWWWWWWNNNNXXKKK000OOOO0KKKK0Okxol:;:::::::::::::::::::::::::::::::::::::::::")
    print("ccccccccccccccccccccccccccccccccccccccc:::;:dO0KKK0Ok0NNNNNNNNXXXXXXXNNNNNWWWWWNNNNXXXKK000OOOOO00KKK0Okdoc:;::::ccccccccccccccccccccccccccccccccccccc")
    print("ccccccccccccccccccccccccccccccccccccccc::::lxO000OOkOXNNNNNNNNNNNNNNNNNNNWWWWNNNNNXXXKK00OOOOOOOO00KK0kxol:;::::cccccccccccccccccccccccccccccccccccccc")
    print("cccccccccccccccccccccccccccccccccccccccc:::lxO0000kkKNNNNNNNNNNNNNNNNNNWWWWWWNNNNXXXKK000OOOOOOOO00KK0kdl:;:::cccccccccccccccccccccccccccccccccccccccc")
    print("cccccccccccccccccccccccccccccccccccccccc:::cdkO00Ok0XNNNNNNNNNNNNNNNNWWWWWWNNNNNXXXKKK000OOOOOOkO00KK0ko:;:::ccccccccccccccccccccccccccccccccccccccccc")
    print("ccccccccccccccccccccccccccccccccccccccccc:::lkO00O0XNNXXXNNNNNNNNNNNNWWWWWNNNNNXXXXKKK000OOOOkkkkO0KKOdc:::ccccccccccccccccccccccccccccccccccccccccccc")
    print("cccccccccccccccccccccccccccccccccccccccccc::cdkOO0XNNNNXXXNNNNNNNNNNNWNNNNNNNNXXXXKKKK000OOOkkkxxddkOxc:::cccccccccccccccccccccccccccccccccccccccccccc")
    print("ccccccccccccccccccccccccccccccccccccccccccc::lxkkOKKK0000KXNNNNNNNNNNNNNNNNNNXXXXKKKKK0000OOkkxdo:;:c:::cccccccccccccccccccccccccccccccccccccccccccccc")
    print("ccccccccccccccccccccccccccccccccccccccccccc::coxkkkxdxOKXNNWNNNNNNNNNNNNNNNNXXXXXKKKK0000OOkkxxdc;;:::cccccccccccccccccccccccccccccccccccccccccccccccc")
    print("cccccccccccccccccccccccccccccccccccccccccccc::cdxxxOKKKXNNWWWWNNNNNNNNNNNNNXXXXXKKKKK0000OOkkxdl:;::cccccccccccccccccccccccccccccccccccccccccccccccccc")
    print("ccccccccccccccccccccccccccccccccccccccccccccc::loox0KXXXNNWWWWWNNNNNNNNNNNXXXXXXKKKK0000OOkkxxo:;::ccccccccccccccccccccccccccccccccccccccccccccccccccc")
    print("lllllllllllllllllllllllllllllllllllllllllccccc::lclxO0000KKXNNNWNNNNNNNNNNXXXXXKKKK0000OOkkxdl:;;:ccccllllllllllllllllllllllllllllllllllllllllllllllll")
    print("lllllllllllllllllllllllllllllllllllllllllllcccc:cc;:clodddxxkO0KKXXNNNNNNXXXXXKKKK000OOOkxxdl::;:cccclllllllllllllllllllllllllllllllllllllllllllllllll")
    print("lllllllllllllllllllllllllllllllllllllllllllllccc:cc::cccclloodxxxk0XNNNNXXXXXKKK000OOOkkxdolclc;:cccllllllllllllllllllllllllllllllllllllllllllllllllll")
    print("llllllllllllllllllllllllllllllllllllllllllllllccc::ldxxkkOOO000KXNNNNNNNXXXKKK000OOOkkxdolloddc::cclllllllllllllllllllllllllllllllllllllllllllllllllll")
    print("lllllllllllllllllllllllllllllllllllllllllllllllcc::coxkOO000KKXNNNNNNNXXXKKK00OOOkkxdolcldkkkdc:ccclllllllllllllllllllllllllllllllllllllllllllllllllll")
    print("llllllllllllllllllllllllllllllllllllllllllllllllcc::ldxkOO00KXXNNNNNNXXXK00OOkkxxdollodxO0OOkxl:ccllllllllllllllllllllllllllllllllllllllllllllllllllll")
    print("lllllllllllllllllllllllllllllllllllllllllllllllllccclxOO0KKXXNNNNNNXXXK00Okxxxdollldk0KKKK0OOxo:ccllllllllllllllllllllllllllllllllllllllllllllllllllll")
    print("llllllllllllllllllllllllllllllllllllllllllllllllllcclxOKKXXNNNNNNNXXK0Okxdoolllodk0KXXXXXXK0Okdcccllllllllllllllllllllllllllllllllllllllllllllllllllll")
    print("lllllllllllllllllllllllllllllllllllllllllllllllllllccok0KXXNNNNNXK0OkdollloodxO0KXXNNNNNNNXK0Oxlccllllllllllllllllllllllllllllllllllllllllllllllllllll")
    print("llllllllllllllllllllllllllllllllllllllllllllllllllllccldk00KKK00OxdoooodxO0KKXXNNNNWWNNNNNXK0Oxoccclllllllllllllllllllllllllllllllllllllllllllllllllll")
    print("llllllllllllllllllllllllllllllllllllllllllllllllllllllccclllollc::lxk0KKXXXNNNWWWWWWWNNNNNXK0Okdccccllllllllllllllllllllllllllllllllllllllllllllllllll")
    print("oooooooooooooooooooooooooooooooooooooooooooooooooolllllccc::;;,';coxO0KXXNNNNNWWWWWWWWNNNNNXKOkdolc::ccllllllllllllooooooooooooooooooooooooooooooooooo")
    print("oooooooooooooooooooooooooooooooooooooooooooooooooolllllccc::;,'':odxO0KXXNNNNNWWWWWWWWNNNNNXK0Oxdolc::::::::cllllooooooooooooooooooooooooooooooooooooo")
    print("ooooooooooooooooooooooooooooooooooooooooooooooooolllllllllllccccodxkO0KXXNNNNNWWWWWWWNNNNNXXK0Okxddoolcc:;;,,:lllooooooooooooooooooooooooooooooooooooo")
    print("ooooooooooooooooooooooooooooooooooooooooooooooooollloddooooollloddxO0KXXXXNNNNNNNNNNNNNNNXXXK00Okkxxddoolcc::clllooooooooooooooooooooooooooooooooooooo")
    print("ooooooooooooooooooooooooooooooooooooooooooooooooolllloddddooooddxxk0KXXXXXNNNNNNNNNNNNNNXXXXKK00OOkkxxddoccclllloooooooooooooooooooooooooooooooooooooo")
    print("ooooooooooooooooooooooooooooooooooooooooooooooooolllcllodddddxxkkk0KKXXXXXXNNNNNNNNNNXXXKKK000OOOkkxxxdolccllloooooooooooooooooooooooooooooooooooooooo")
    print("oooooooooooooooooooooooooooooooooooooooooooooooooolllcclloddxkOOO0KKKXXXXXXXXXXXXXXKKKK000OOOkkkxxxdoolllllloooooooooooooooooooooooooooooooooooooooooo")
    print("ooooooooooooooooooooooooooooooooooooooooooooooooooooollllclloodxxkOO0KKXXXKKKKKKK00000OOOkkxxdooollccclllloooooooooooooooooooooooooooooooooooooooooooo")
    print("oooooooooooooooooooooooooooooooooooooooooooooooooooooooollllllcccllllooddddxxxxxxxxxxxxddoollccclllllloooooooooooooooooooooooooooooooooooooooooooooooo")
    print("oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooolllllllllllllccccccllllccllllllloooooooooooooooooooooooooooooooooooooooooooooooooooooo")
    print("oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooolllllllllllooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo")
    print("oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo")
    print("oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo")
    print("oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo")
    print("oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo")
    print("dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddooooo")

def St_Pepsi_Art01():
    print("kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk")
    print("kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk")
    print("kkkkkkkkkkOOkkkkkkkkkkkkkkkkkkOOOOkkkkOOOOkkOOOOkkOOkkkkOOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk")
    print("kkkkkkkkO0OOkkkOKOkkO00KOkkk0OO00OkkkO00O0O00OOOO00O0Ok0OOOOOOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk")
    print("kkkkkkkkOOOOkk0000kO00000OkO0kk0Oxkkk00kkO000OOkO0kkO0OOOOkO0kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk")
    print("kkkkkkkOOOOO0OkkkO0O00OkkO0KOkOOkkkkO0OkkkO0OOOO0OkkkOOOOOO0Okkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk")
    print("kkkkkkkkkkO0OO0O0KOO00OkO0O0OkO0kkkkk00OOOO0OOOO00OOOkkkkO00Okkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk")
    print("kkkkkkkkOOOkkkkkkkOkkkkkkkOOkkkkkkkkkkkkkkOOOOOkkkkkkkOOOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk")
    print("kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk")
    print("kkkkkkkkkdoooooodkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk")
    print("kkkkkkkdl:;;;;;:ldkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk")
    print("kkkkkxl:;;;;;:codxkkkkkkkkxxxxxxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk")
    print("kkkxo:;;;;;:codxkkkkkkkkdl:::;::lxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk")
    print("kkkxdolllllodxkkkkkkkkdl;;;;,,,,;cllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllldkkkkkk")
    print("kkkkkkkxxxkkkkkkkkkkdl:;;;;,''''',,,,,,,,''''''''',,,,,,''''''''''''''',,,,,,'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''.:kkkkkk")
    print("kkkkkkkkkkkkkkkkkkkkkxddxdd;.::::::::;;;;;;;,,,,;:::::::::;;;;;;;::::::::::::::::::::;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;.:kkkkkk")
    print("kkkkkkkkkkkkkkkkkkkxoc::::c'.;::::::::::;;;;;;,,,;::::::::::::::::::::::::::::::::::::::::::::::::;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;.:kkkkkk")
    print("kkkkkkkkkkkkkkkkkkkkkkkkkkk:.;::::::;;,,;,,,,,;:::::::::;;;;;;;,;;;:::::::::::::::::::;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;.:kkkkkk")
    print("kkkkkkkkkkkkkkkkkkkkkkkkkkk:.::::::::;;;;;;;;:::::::::;;;;;;,,,,,;;:::::::::;;;;;;;;;;;;;;;;;;;;::;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;.:kkkkkk")
    print("kkkkkkkkkkkkkkkkkkkkkkkkkkk:.:::::::::::::::::::::::;;;;;;,,,,,;:::::::::;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;.:kkkkkk")
    print("kkkkkkkkkkkkkkkkkkkkkkkkkkk:.;::::::::::::::::::::::;;,,,,,,,;:::::;;;;;;;;;;;,,,,,;;:;;;;::;;;;;;;;::;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;.:kkkkkk")
    print("kkkkkkkkkkkkkkkkkkkkkkkkkkk:.;::::::::::::::::::::::::;;;;;;:::::::;;;;;;;;;;,,',,;;;;:;::;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;.:kkkkkk")
    print("kkkkkkkkkkkkkkkkkkkkkkkkkkk:.;::::::::::::::::::::::::::::::::::::::;;,,,,,,,,,;;;;;;;;;;;;;;;;,,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;.:kkkkkk")
    print("kkkkkkkkkkkkkkkkkkkkkkkkkkk:.;::::::::::::::::::::::::::::::::::::::;;;;;;;;;;;;;;;;;;;;;;,;;;,,,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;.:kkkkkk")
    print("kkkkkkkkkkkkkkkkkkkkkkkkkkk:.;:::::::::::::::::::::::::::::::::::::::;;;::::;;;;;;;;;;;;;,,,,,,,;;;;;;;;;;;;;;;;,,,,;;;;;;;;;;;;;;;;;;;;;;;;;;.;kkkkkk")
    print("kkkkkkkkkkkkkkkkkkkkkkkkkkk:.;;;;:::::::::::::::::::::::::::::::::::::;;:::::;;;;;;;;;;,,,,,,,;;;;;;;;;;;;;;;;,,,',,;;;;;;;;;;;;;;;;;;;;;;;;;;.;kkkkkk")
    print("kkkkkkkkkkkkkkkkkkkkkkkkkkk:.;;;;:::::::::::::::::::::::::::::::::::::;;;;:::;;;;;;;;;;;;;;;;;:;;;;;;;;;;;;;;,,',,;;;;;;;;;;;;;;;;;;;;;;;;;;;;.;kkkkkk")
    print("kkkkkkkkkkkkkkkkkkkkkkkkkkk:.;;;;;:::::::::::::::::::::::::::::::::::::;;;:::;;;;;;;;;;;;;;;;;;;::;;;;;,,,,,,,,;;;;;;;;;;;;;;;;,,,,;;;;;;;;;;;.:kkkkkk")
    print("kkkkkkkkkkkkkkkkkkkkkkkkkkk:.;;;;;::::::::::::::::::::::::::::::::::::::;;:::;;;;;;;;;;;;;;;;::;::;;;;;;;;;;;;;;;;;;;;;;;;;;;,,,,,;;;;;;;;;;;;';oodkkk")
    print("kkkkkkkkkkkkkkkkkkkkkkkkkkk:.;;;;;;:::::::::::::::::::::::::::::::::::::;;::::;;;;;;;;;;;;;;;;:;;:;;;;;;;;;;;;;;;;;;;;;,,,,,,,,,;;;;;;;;;;;;;;;;;:ldkk")
    print("kkkkkkkkkkkkkkkkkkkkkkkkkkk:.;;;;;;:::::::::::::::::::::::::::::::::::::;;;::::;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,,,,,,,,;;;;;;;;;;;;,;;;,;cldxkk")
    print("kkkkkkkkkkkkkO00OOkkkkkkkkk:.;;;;;;;:::::::::::::::::::::::::::::::::;;:;;;;::::;;;;;;;;;;;::;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,,;,,.,dxkkkk")
    print("kkkkkkkkkkkkkO0XXXKK000OOkk:.;;;;;;;;::::::::::::::::::::::::;;;;;;;;;;::;;;;;::;;;;;;;;;;;;::;;:;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,,,,,,,.;kkkkkk")
    print("kkkkkkkkkkkkkkkkk0XXXXXXXXNXKd:;;;;;;:::::::::::::::::::::::::::::::::::::;;;;:::;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;.:kkkkkk")
    print("kkkkkkkkkkkkkkkOKXXXXNXXXKKxc;;;;;;;;:::::::::::::::::;;;;;;;:::::::::::::;;;;::;;;;;;;;;;;;::;;:;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;.;kkkkkk")
    print("kkkkkkkkkkkkkkkkkkOKXXXXXXXXXKx:;;;;;;:::::::::::::::::::::::::::::::::::::;;;;:::;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;.:kkkkkk")
    print("kkkkkkkkkkkkkkkkkkkk0XXXXXXXXXXkc;;;;;;:::::::::::::::::::::::::::::::::::::;;;:::;;;;;;;;;;;;:;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;.:kkkkkk")
    print("kkkkkkkkkkkkkkkkkkkkkOKXXXXXXXXXOc;;;;;::::::::::::::::::::::::::::::::::::::;;;::;;;;;;;;;;;;;:;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;.:kkkkkk")
    print("kkkkkkkkkkkkkkkkkkkkkkk0XXXXXXXXX0l;;;;;:::::::::::::::::::::::::::::::::::::;;;:::;;;;;;;;;;;;::;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;.:kkkkkk")
    print("kkkkkkkkkkkkkkkkkkkkkkkkOKXXXXXXXX0o:;;;:::::::::::::::::::::::::::::::::::::;;;;:::;;;;;;;;;;;::;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;.:kkkkkk")
    print("kkkkkkkkkkkkkkkkkkkkkkkkkk0XXXXXXXXKd:;;:::::;:::::::::::::::::::::::::::::::;;;;:::;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;.:kkkkkk")
    print("kkkkkkkkkkkkkkkkkkkkkkkkkkkoxXXXXXXXKx:;;:::::::::::::::::::::::::::::::::::::;;;::::;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;.:kkkkkk")
    print("kkkkkkkkkkkkkkkkkkkkkkkkkkk:'dKXXXXXXXkc;;::::::::::::::::::::::::::::::::::::;;;;:::;;;;;;;;;;;;;;::;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;.:kkkkkk")
    print("kkkkkkkkkkkkkkkkkkkkkkkkkkk:':lOXXNXXXXOc;::::::::::::::::::::::::::::::::::::::;;;::;;;;;;;;;;;;;;;;;;;;;;;;;;,,;,,,,,,,,,,,,,,,,,,;;;;;;;;;;.;xkxxxk")
    print("kkkkkkkkkkkkkkkkkkkkkkkkkkk:.;:cdKXXXXXXOl::::::::::::::::::::::::::::::;;;;;;;;;;;;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;;;,,;,,,,,,,,,;;;;;;;;;;;;;;.;xkkkxk")
    print("kkkkkkkkkkkkkkkkkkkkkkkkkkk:.::::lOXXXXXX0o:::::::::::::::;;;;;;;;,,,,,,,,,,,,,,,,,;;;;;,,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;.:kkkkkk")
    print("kkkkkkkkkkkkkkkkkkkkkkkkkkk:.:::::cd0XXXXXKd:::;;;;;;;,,,,,,,,,,,,,,;;;;;;;;;::::;;;:::;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;.:kkkkkk")
    print("kkkkkkkkkkkkkkkkkkkkkkkkkkk:.;:::::;lkXXXXXKd;,,,,,,,;;;;;;;;;;::::::::::::::::::;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;.:kkkkkk")
    print("kkkkkkkkkkkkkkkkkkkkkkkkkkk:.;;;;;;,,;o0XXXXXx:;;;:::::::::::::::::::::::::::::::;;;;;::;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;.:kkkkkk")
    print("kkkkkkkkkkkkkkkkkkkkkxxdddo;.,,,,,,;;,;ckXXXXXOl::::::::::::::::::::::::::::::::::;;;;::;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;.:kkkkkk")
    print("kkkkkkkkkkkkkkxxddddooooodd;.;;:::::::;;:d0XXXX0l::::::::::::::::::::::::::::::::::;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;.:kkkkkk")
    print("kkkkkkkkxdoooollooddxxxxxkk:.;::::::::;;;;lkXXXX0o:::::::::::::::::::::::::::::::::;;;;;;::;::::;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;.:kkkkkk")
    print("kxxdddollllodddxxkkkkkkkkkk:.;:::::::::;;;;:d0XXXKd::::::::::::::::;::::::::::::::::::::::;;;;;;;;;;;;;;:;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;.:kkkkkk")
    print("oollodddxxxkkkkkkkkkkkkkkkk:.;:::::::::;;;;;;ckXXXKx:::::::::::::::::::::::::::::;;;;;;:;;;;::;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;.:kkkkkk")
    print("ddxxxkkkkkkkkkkkkkkkkkkkkkk:.;:::::::::;;;;;;;:d0XXXkc::::::::::::::;;;;;::::::::::::;;;;;;::::;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,;,.;kkkkkk")
    print("kkkkkkkkkkkkkkkkkkkkkkkkkkk:.;::::::::::;;;;;;;:lkKXXOl::::;;;;;;::;;;;;;:::::::::::::::;;;;:::;:;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,.;kkkkkk")
    print("kkkkkkkkkkkkkkkkkkkkkkkkkkk:.;::::::::::::::::::::d0XXOl::;;;;;;;::;;;;;;;::::::::::::::::;;;::;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;.:kkkkkk")
    print("kkkkkkkkkkkkkkkkkkkkkkkkkkk:.;:::::::::::::::::::::lkKX0o:;;;;;;;:::;;;;;;::::::::::::;;;;;;;::::;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;.:kkkkkk")
    print("kkkkkkkkkkkkkkkkkkkkkkkkkkk:.;:::::::::::::::::::::::d0XKd:;;;;;;;::;;;;;;::::::;;;;;;;;;;;;;;;:::;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;.:kkkkkk")
    print("kkkkkkkkkkkkkkkkkkkkkkkkkkk:.;:::::::::::::::::::::::;lkXKx:;;;;;;:::;;;;;;::::;;;;;;;;;;;;:;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;.:kkkkkk")
    print("kkkkkkkkkkkkkkkkkkkkkkkkkkk:.;::::::::::::::::::::::::::d0Xkc;;;;;;::;;;;;;;;:::;;;;::::;;;:::;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;.:kkkkkk")
    print("kkkkkkkkkkkkkkkkkkkkkkkkkkk:.;;;;::::::::::::::::::::::::lkKkc;;;;;:::;;;;;;;:::::::::::;;;:::;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;.;kkkkkk")
    print("kkkkkkkkkkkkkkkkkkkkkkkkkkk:.;;;;;;::::::::::::::::::::::::d0Ol;;;;;::;;;;;;;;::;;;::::::;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;.:kkkkkk")
    print("kkkkkkkkkkkkkkkkkkkkkkkkkkk:.;:;;;;;;:::::::::::::::::::::::lkOo;;;;:::;;;;;;;::::::::;;;;;::;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;.:kkkkkk")
    print("kkkkkkkkkkkkkkkkkkkkkkkkkkk:.:::::;;;;;:::::::::::::::::::::;:dko:;;;::;;;;;;;::::::;;;;::::;;;;;;;:;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;.:kkkkkk")
    print("kkkkkkkkkkkkkkkkkkkkkkkkkkk:.::::::;;;;;;:::::::::::::::::::::;cxd:;;;:;;;;;;;:::;::;;::;;;;;;;;;;;:;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;.:kkkkkk")
    print("kkkkkkkkkkkkkkkkkkkkkkkkkkk:.;:::::::;;;;;;;:::::::::::::::::::;:lo:;::;;;;;;;;:::::;;;;;;;;;;;::;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;.:kkkkkk")
    print("kkkkkkkkkkkkkkkkkkkkkkkkkkk:.::::::::::;;;;;;;:::::::::::::::::;;;cl:;::;;;;;;;;:;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;.:kkkkkk")
    print("kkkkkkkkkkkkkkkkkkkkkkkkkkk:'::::::::::::;;;;;;::::::::::::::::;;;;:::::;;;;;;;;;:::::;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;.:kkkkkk")
    print("kkkkkkkkkkkkkkkkkkkkkkkkkkk:'::::::::::::::;;;;;::::::::::::::::;;::;:::::::::::::::::;;;:::::::;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;.:kkkkkk")
    print("kkkkkkkkkkkkkkkkkkkkkkkkkkk:.',,,,,,,,,,,,,,'''',,,,,'',,,,,,,,,'',''',','''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''.:kkkkkk")
    print("kkkkkkkkkkkkkkkkkkkkkkkkkkkdlcclllllllllllllllllllllllcllllllllllllcclllllllllllllllllllllllllllllllllllllllllllllllllllllllllllcllccclllclllcldkkkkkk")
    print("kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk")
    print("kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk")
    print("kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk")

def floral_shoppe_art():
    print("';:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::;:;;;,,,,,,,,;;;;;;")
    print(",dkxxxxxxxxxkxdddxxxxxxkkkkkkkxxxxxxxkkkkxxxxxxkkkkkxxxxxxxxxkkkkkkxxxxxxkkkkkkxxxxxxxxxkkkkkkxxxxxxxxxxkkkkkkxxxxxxxxkkkxxkkkxxxxxxdoolcccc:cccoooooo")
    print(",dkkxxxkkkxooollloldxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxkxdoolllllccccoddddo")
    print(",dkkkdddxxxddkOOOkxdddxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxdoollllllllloddddd")
    print(",xOkkkxxxkOOkkkOkxkkkkxkkkkkkOOkkkOOOOOOOOkkkkkkkkkkkkkkkkkkkkkkkkkkOOkOOOOOOOOOOOOOkkOOkkkkkkkkkkkkkkkkkkkkkkkOOkkOOOOOOOOkkkkkdcccc:::::::::::cc::ld")
    print(",xOxdddooxOOkkkOOOkxkkxkkkOOkOOOOOOOOOOOOOOOOOOOOOkkkkkkkkkkkkkkkOOOOOOOOOOOOOOOOOOOOOOOOkkkkkkkkkkkkkkkkkkkkkOOOOOOOOOOOOOOOkkkl.'cc;:l::l:;l:;lc..cd")
    print(",dxddooolokOOOkkOOkddxkkkxkkkkOOOOOOOOOOOOOOOOkkkkkkkkkkkkkkkkkkkkkkOOOOOOOOOOOOOOOOOOOOkkkkkkkkkkkkkkkkkkkkkkkOOOOOOOOOOOOOkkkko;;clcclccl::c::lc,;ld")
    print(",odooooooooddkkxxkkxdkOd:;;;::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::;;;;;;;;;;;;;;;;;;;;;;")
    print(",lllllllllooooddxxOkdddo:clooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo")
    print(",looooollooooocloloddllooloooddxxkkkkkkxxdddddddoddddddxxxxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxxxxkxxkkxxkkxkkk")
    print("'ldoooolllodddc:llloddddddddoddxxkxxxxdolllooddooodddddxxdodddxxxxxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxxkkkkkkOOOO0OOOkxkkk")
    print("'oxddddoddoddd:;llloodxxxxxxxxxxxkxdxdl:;,;coxxddxxddddolcccloodddxxxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOOOxk000K0KOxxkkk")
    print(",okxddoodxkkkx;,lodddxxkkkkkkkkkkxoooc;;''';lxkdodddoooolooolc:codxdddxxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxxOOkkkxO000Oxxkkk")
    print(",okxdoodxkkOOk;;odddxkkkkkkkkkkxkxl:loooc;;,':dddxdooodddddool:;;codxdddxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxxOkxk0OkkkOKOxxkkk")
    print(",oxxxxxkkOkkOk;;xxxxkkkkkkkkkkkxxd:,;:clodo;;coxxkdcclooolcccoxd:;coodxdddxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxOkddkOkkkxk0Okkkkxxkkk")
    print(",oxxkkkkOOOOOk:;xkkkkkkkkkkkkkxdl:,',:::;;:ccccldkl:ccodl;,,,:lxd::odxOxooxxxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxOkxkOxxOOkkkkOOxxxxkkk")
    print(",oxxkkkkkOOOOk:;xkkkkkkkkkkkkxo;;;;;:cc::clllccloxoooodoloooc::odc,:ldxkxddddxxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxOkxkkkOkxOOkxkxdxxkkkk")
    print(",oxxkkkkkOOOOk:;xkkkkkkkxkkkkdc;,,;:looccooolcloodddddxxxxxxxdllodl;;coxkOOkkxxxxxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxO00kxkOkxxkkxdxxkkkkkk")
    print(",okkkkkkOOOOOk:;xkkkkkkkkkkxollll::lodl,;odddddxxxxxxxkkOOOOOOOxoddolloollloxkkxxddxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOOkxxxxxxxxxxxkkkkkkk")
    print(",okxkkkOOOOOOk:;xkkkkkkkkkdlcodoccloodlcldodddddddxxxxkkOO00KKKKOxdoooooc::;;oOkxxddxkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkkkkkkkkkkkOOOOkkkkkk")
    print(",oxxkkkkOOOOOk:;xkkkkkkkxxo:codoccloolllodddxddxxxxxxkkOO0000KKKKK0kxoldddxkddOkkkxddxkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkxxkkk")
    print(",oxxkkkkkOOOOk:;xkkkkkkkxkd::loollooooddddxdxxxxxxxkkOOO000000KKKKKK0dclddxOOkxkkxoclodxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxkkx")
    print(",oxxkkkkkkOOOk:;xkkkkkkxkkxdl:coolcloddoodxdxxxxxxkkOO00000000000KKKKOc:odooxOOOkdccodxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxxkkk")
    print(",oxxkkkkkkOOOk;;xkkkkkkkkkxxdl:cc:;:ccccoxxxxxdxxxkkOO000000000KKKKKK0l,:oooodk0kocldxxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkx")
    print(",oxxkkkkkkkkOk;;xkkkkkkkkkxkxo:;,,;:c:;:oxxxxxxxxxkkOO000000000KKKKKKKx;,clolldxdclodxkkkkkkkkkkkkkkkkkkkkkkkkkkxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk")
    print(",oxxkkkkkkkkOk;;xkkkkkkkkkkkxl;,''';;,':dxddddxxxxxkOO00000000KKKKKKKKO:':clc:colcloddxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxdddddxxxxxxxxxddddddddddddddxkkkk")
    print(",oxxkkkkkkkkOx;;xkkkkkkkkxkkxl;;,,;;;;,cdxdddddddxxkOO0000KKKKKKKKKKKKKd;cdxxdoddc;;:ccccccccccllllllllooddoooooooc::;;;;;:ccllccc::;,''''......,oxkxk")
    print(",oxxkkkkkkkkOx;;xkkkkkkkkkkxdlc::cc,;;;lxxdddddxxxxkkO000KKKKKKKKKKKKXX0llxxxxxxxc,,;::::cc::;;::cccllloddddoooool:;;:;;;;;::cccc::;,...........'lxxkk")
    print(",oxxkkkkkkkkOx;;xkkkkkkkkkxxdlllloo:::;lxxddxdxxxxxkkO000KKKKKKKKKKKXXXKxdkkkkkkko,,:::ccc:;;;;;:llllllooolldxddoc:;;:ccccccccccc:;'............'lxkkk")
    print(",oxxkkkkkkkkOx;;xkkkkkkkkkkxdllloxxc:;,cxxddddxxxxxkkO000KKKKKKKKKKKKKKKkdkOOOkkkl,,:cccclc:;;;;:lllloooddlcloodxolccccc:::ccccc:,'.............'lxkkk")
    print(",oxxkkkkkkkkOk;;xkkkkkkkkkxxxdoodooc;,.:dxxdxddxxxxkkO00KKKKKKKKKKKKKKKK0kdxkOOOkc',:cccclc:;;,,:llloooodddollodxxdlcc;'....',:;,...............'lxkkk")
    print(",oxxkkkkkkkkOk;;xkkkkkkkkkkkxxoloooc,'':dxdxxddddxxkkOO0KKKKKKKKKKKKKKKKKKOOOkkkd;';:::cccc;,;;,:oooooollllloolcll:,'''.......''................'lxkkk")
    print(",oxxkkkkkkOOOk;;xkkkkkkkkkkkkxoc::c;,,;cdxxxddxxdxxxkOO00KKKKKKKKKKKKKKKK000kdxko,.,,;:::;:;,;;,:oooodo;''.''''.',,'''.........'................'lxkkk")
    print(",oxxkkkkkOOOOk:;xkkkkkkkkkkkkxl;;;:;;;,;lxxdddddddxxxkO0KKKKKKKKKKKKKKKKxccloxOOd,..'',,.',,,,'';lol;;:,................................''...',',lxkkk")
    print(",oxxkkkkkOOOOk:;xkkkkkkkkkkkkxd:;,,,,;;;lxxddxddddxxxkO0KKKKKKKKKKKKKKKOc,:ldOOOo,'''''....'''..',,'.........................................,,;:lxkkk")
    print(",oxxkkkkkOOOOk:;xkkkkkkkkkkkkxxo:,,,;::;lxxxddxxxxxxxkO0KKKKKKKKKKKKKKKxccoodO0kc,,;;;,.....................................................';;;;lxkkk")
    print(",oxxkkkkOOOOOk:;xkkkkkkkkkkkkxxxdc::cc;:oxxxxdxxdxxxxkO0KKKKKKKKKKKKKKOllxxxkO0d:''',,,.....................................................';;',lxxkk")
    print(",okxkkkOOOOOOk:;xkkkkkkkkkkkkkkxxdoc:::ldxdxddddddddxkO00KKKKKKKKKK0K0ocdxddxOxl:,...'................................''........................'lxxkk")
    print(",okxkkkOOOOOOk:;xkkkkkkkkkkkkkkkxxxdlcldxxddddddoooddxkO0KKKKKKK00OO0k:cdxxxxdccc:;;:ccllllooooooooooooooooolllllcc:::;;,,'''''''''''''',,'',,;;:oxkxx")
    print(",oxxkkkkkOOOOk:;xkkkkkkkkkkkkkkkkkkxdoodxxddddddooooodxOO00OOOkkkkO0Kd;ldxxxdccllc:cllooddxxkkkkOOOOOOOOOOOOOkkkxxxdollcc::;;;;:::::ccccc:::c:cccoxkkk")
    print(",oxxkkkkkkOOOk:;xkkkkkkkkkkkkkkkkkkkxxddxdddddddoooooooodddddxkkOKKXKl;odxdocclddc;:cclloodxxxkkkkOOOOOOOOkkkkxxxddolcc:::;;:::::ccccccc::::;;:::oxkkk")
    print(",oxxkkkkkOOOOk:;xkkkkkkkkkkkkkkkkkkkxxxxxxxddddddddxxxxkkOO00KKKKKKX0c:odkdlcldddc,,;;::cclloodxxkkkkkkkkkkxxxdoollcc:::::::::ccccccccccccc,.'::coxkkk")
    print(",oxxkkkkkOOOOk;;xkkkkkkkkkkkkkkkkkkkxxxxxxxxkkkkkkOOOOO0KKKKKKKKKKKXkcldxdlccodxdc;,,,,,,,,,;;:clllooodddxkkkxxxxxxxddoooollccccccccccccccc;,,::coxkkk")
    print(",oxxkkkkkkOOOk;;xkkkkkkkkkkkkkkkkkkxxxxxxxkkOOO00OOOO000KKKXXXKKKKX0o:clllloodxxdllllllllllllooddxkkOOOO0KKKKKKKK00Okxddoolllccccccccccccccc::::coxkkk")
    print(",okxkkkkkkkOOk;;xkkkkkkkkkkkkkkkkxxxdxxxxkkOO00000000000KKKXXKKKKKKkccloodddxxxxdxkOOOOO00000000000000OOOOOkkxdddooolcccccc:ccc:ccccccccc:cc::::coxxkk")
    print(",oxxkkkkkkkkOk;;xkkkkkkkkkkkkkkkxxxxxxxxkkkOOO000KKK0O000KKKKKKKKX0ocldxxxxxxkkxdxOOOOOkkkxxxddooooooooooooloolcclllccc:ccc::cc:cccccccccc:cc:::coxxkk")
    print(",oxxkkkkkkkkOk;;xkkkkkkkkkkkkkkxdoxkkkxxkkkkOO00KKKKK00O000KKKKKKKkccoxxkkkkkkkxdooolllllllllllllooodddddddooooololccccc:cccccccccccccccccccccc:coxxkk")
    print(",oxxkkkkkkkkOx;;xkkkkkkkkkkkkkkxooxkOkkxxkkkO000KKKKXKKKKKKKKKKKK0ocldxkkkkkkkkxdlccccllcccllllooddddxxxxxddddoolllcccccccccccccccccccclccllccllcoxkkk")
    print(",oxxkkkkkkkkOx;;xkkkkkkkkkkkkkkxodkOOkkkkxkkOO00KKKKXXXXXXXXXKKKKxcloxxkkkkkkkkxdlc:ccccclllooodxxxxxkkkxxdddooollcccccccc::ccc:ccccccclccllllllloxkkk")
    print(",oxxkkkkkkkkOx;;xkkkkkkkkkkkkkkxook0OOkxxkkkOO00KKXXXXKKKKKKKKKK0ocodxxkkkkkkxxxxoc:cc:::ccccccllllloollolclcclc::::c:::::::::::::::c::::::::::cloxkxk")
    print(",oxxkkkkkkkkOx;;xkkkkkkkkkkkkkkxdoxkOOkxxxkkOO00KKKKKXXXKKKKKKKXOocodxkkkkkkkkkkxxdoooooooooooooooooooooollllooooooooloollllloolloollllllllllllllodddo")
    print(",oxxkkkkkkkkOk;;xkkkkkkkkkkkkkkkxddddxxxkkkxkkOOOOkk00KXXKKKKXXXk:;cllloooodddooloollollllloolllllolllllllclllloolllccllllccccllc:cllcllcclllcc;::c:;,")
    print(",oxxkkkkkkkkOk;;xkkkkkkkkkkkkkkkxxxddoddxxkkkxkOOOOOOk0KXKKKKXXXOc;::cc:cc:;;;;;;;;:cc::::cc:::::cc:;:;;::::cccccll:;;;;:;,;:ccc:codoc;;;;;;,...,;:ccc")
    print(",oxxkkkkkkOOOk;;xkkkkkkkkkkkkkkkkkkxxxxxxxxxxxxxkkO000KXXKKKKKKXKOo;,,',:lc:::::cl;,;;;;;;:c:::::cc:;;;;;;loc:::::,.,;;::::lxxl:;;;;,'...;cc:cccloxxxd")
    print(",oxxkkkkkkOOOk;;xkkkkkkkkkkkkkkxxkkxxxkkO0000OOOOOOOO0XXXK00KKKKKK0xc;''''''.''.;llllllloc,,,,,,,;cccc:::::;,;;;;;;:oxl:;;;;;,'..,:cccccldxkdl;,''''''")
    print(",oxxkkkkkOOOOk:;xkkkkkkkxxxxxxxxxddddxkOO00KKKXXXXXK00KXKKKKKKKKKXXOoloooollooc,''''''',:lllllllllc,','',,,,cocccc::cc,.,:;;:::::lxxoc;;;;,,,,...',:cc")
    print(",oxxkkkkkOOOOk:;xxxxkkkkkkkkkkkxxxddxkkOO00KKXXXXXNNXXXXXNNNNNNNXXXKOOOkkxxdxddddxxxxxl'..........cddddddddddl,.........;oxdoooooollc;..'',,,,,,,,:ldx")
    print(",oxxkkkkkOOOOk:;xxxxxxkkkkkkOOOOOOOOOOOOO000KKKKKKKKKKXXXKKKKKKKKKKKKKKXXKXNk;.''''''collloooooooo:............:ddddxxxxxxxl'...       .':oxkkkkkkkkkk")
    print(",oxxkkkkOOOOOk:;dxxxxxxxxxxxxxkkkkkkkOOOOOOOOOOOOOOOOO0000KKKKKXXXXXXXXXKKXXd.......'coooooollllll:''''''',',,,:olcccc::::::;',:::::::::::ldxo:;,,,,,,")
    print(",oxxkkkkOOOOOk:;dxxxxxxxxxxxxxxxxxxxxxxxkkkkkkkkO0KKKKKXXXXXXXXXXXXXXXXKKXXXkccoddd:............ .:xxxxxxxxxxkkkx:.           'cdkkkkkkkkkkkkxo:'.    ")
    print(",oxxkkkkOOOOOk:;dxxxxxxxxxxxxxxxxxxxxxxxkxxxxxxx0XXXXXXXXXXXXXXXXXXXKKKKKKXXkcldxxl...............:ddddddddddooooo;......''.''',cxdllccccccccccc:'..',")
    print(",oxxkkkkkkOOOk:;dxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxk0XXXXXXXXXXXXXXXXXXKKKKKKKXKo...'ldloooooooooooood:................,oxxxxxxxxxxxxkd:.               .;")
    print(",okxkkkkkkkkOk;;dxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxk0XXXXXXXXXXXXXXXXXKKKKKKKKXXo.  ;dkxkxxkkkkkkkkkkk:.                'oxxkkkkkkkkkxkxo;.             ..")
    print(",oxxkkkkxooodd;;dxdxxxxxxxxxxxxxxxxxxxxxxxxxxxxk0XXXXXXXXXXXKKKKKKKKKKKKKKKXd'.':ccccccccccc:::::c:;;;;;;;;::::::::::ol;,,,,,,,,,,,'''.'cllllllllolooo")
    print(",oxxkkkko,'''c;;dddxxxxxxxxxxxxxxxxxxxxxxxxxxxxkKXKXXKKKKKKKKKKKKKKKKKKKKKKXkc,.                  ;xkxkkkkkkkkkkkkkkkkd,                .cdkxkxxxkkkkk")
    print("'oxdxxdxl,:l:c;;ddddxxxxxxxxxxxxxxxxxxxxxxxxxxdkKXKKKKKKKKKKKKKKKKKKKKKKKKKXk,.                   ;xxxxkkkkkkkkkkkkkkkkd;.                .cdxkkkkkkkk")
    print("'looooooc,:c:c;;dddxdxxxxxxxxxxxxxxxxxxxxxxxxxdkKXKKKKKKKKKKKKKKKKKKKXKKXK00o....................':oloolllllllllllllllllc,,,,,,,;;,;;;;;;;;:odl;;;;;;;")
    print(",cclloloc;:l:c;;dxdxxxdddddxxxxxxxxxxxxxxxxxxxdkKXKKKKKKKKKKKKKKKXKXX0ko:;:lccloodddddddddddddxxxxc..... .               .:xkxkkxkkkkkkkkkkkkxl,.     ")
    print("'::cllloc,:l:c;;dxdddxxxxxxxxddxxxdddxxxxxxxdddx0XKKKKKKKKKKKKXXX0xl;.. .;odddxxxxkkkkkxkkkkkkkkxkc.                      .;dkkkkkkkkkkkkkkxxkkxo,.   ")
    print("'::cllllc,:l;:,;xxdooooddddxxxxxxxxddddxddxddddx0KKKKKKKKXXXKOdc;.     .cxxxxxkxkkkkkkkkkkkkkkkkkkl.                        ,dkxxkkkkkkkkkkxxxkkxxl'. ")
    print("'::cccclc;cc;:;;xxxxxdooooooooodxxxxxddddddddddxKXKKKKXXKkdc'.        .cxkxxkkkxkxxxxxxxxxxxxxxxxxl..........................:dooooooooolllllllllllc,.")
    print("'cllllloc;cl::,;xkkkkxxxxxxddooooooooddxxxxxdddxKXXXKOkdl;,,;;;:::::c;''''''''''''''''''''''''''.':ddooooooddddddddddddddddxddd;...                   ")
    print("'ldoddddc,;:;:,;xkkkkkkkkkkkxxxxxdddooooododdddk00kdolcloodxxxxkxxkkx;                            ,xkxkkkkkkkkkkkkkkkkkkxkkxkxkd,                     ")
    print("'cooddddl:;;:c,;xkkkkkkkkkkkkkkkkxxxxxxdddooooooolcloodxxxxkkkkkkkkx;                             ,xkkkkkkkkkkkkkkkkkkkkkkkxkkxkd;                    ")
    print("'coooddddddddo,;xkkkkkkkkkkkkkkkkkkkkxxxxxxxxdddddddxxxxkkkkkkkkxkkl.                             ,xkxkkkkkkkkkkkkkkkkkkkxxkkkkkkd'                   ")

def surfing_art():
    print("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM")
    print("MMMMMMMMMMMMMN0xdxddONMNOdOWMXxdKMNOodxxdxKWMNOddxxx0WNkd0WWKdokXWXxd0WMNOddxxdx0NMMMMMMMMWMXkdON0dOXkxKKxd0WMMKxkXKkXWOOK0KkdkXOOWNkd000N0KMMMMMMMMMM")
    print("MMMMMMMMMMMMWk.    ''OMXc.cNM0'.kWXc.    .,0MXc.     WK;.oNNd. 'kW0,.dWNo.     ''kWMMMMMMMWMOlookooX0ldNklll0MWxcONx,kNc:doOx:kX::XkcldddOokMWMWMMMMMM")
    print("MMMMMMMMMMMMWx.'OMK:,OMXc.cNM0'.kWXc.lNMk.'OMXc.lXMWWMK;.oNNd. .cX0,.dWXl.cOXMK:,kWMMMMMMMWMOokdxdxM0lOMkoxo0MMxoNWd'xNc,ooKOl0K:;Kkoxxkddd0MWMMMMMMMM")
    print("MMMMMMMMMMMMM0;.lXWXKNMXc.cNM0'.kWXc.lNMk.'OMXc.lNMMWMK;.oNNd...'O0,.dWXl.cOXMWXKNMMMMMMMMWMOokdxdxM0lOMkoxo0MWxoNNd;xXl'coKOl00c:0OlONXdcdNMMMMMMMMMM")
    print("MMMWWWMMMMMWMWXo';xNWWMXc.lNM0'.kMXc.;kkc.cKMXc.;xOOKWK;.oNWd.,:'lk,.dWNl.cOXWWWWWMMMMWMMMWMOokdxocK0coXklllKMWx:k0dcdKo,:lKOl0OllONdoNWx;xWMMMMMMMMMM")
    print("MMMWWWMMMMMMWWWW0c':OWMXc.cNM0'.kWXc.    .cKMXc.    KWK;.oNWd.;x:,l,.dWXl.cOKKxcc0WMMWMMMMWMOokdxocK0coXkcdKWMMx:kOdodOd:;cKOl0kooxWKlxWk:OMWMMMMMMMMM")
    print("MMMMMMMMMMMMWNXNWNx.'OWXc.cNM0'.kWXc.lNMk.'OMXc.lNMMMMK;.oNNd.;0d.'..dWXl.cOXW0,.xWMWWWMMMWMOokdxdxM0lOMkoXMWMMxoNOc:lkdc;:KOl0xccdNWklKOl0MWMMMMMMMMM")
    print("MMMMMMMMMMMMWk;lXMK,.dWXc.cNM0'.kWXc.lNMk.'OMXc.lNMWWMK;.oNNd.,KK;...dWXl.cOXM0,.xWMWWMMMMWMOokdxdxM0lOMkoXMWMMxoNkodlxdo;;KOoOdoooxkkl0Ol0MWMMMMMMMMM")
    print("MMMMMMMMMMMMWd.    ,.dWXc.    ..kWXc.lNMk.'OMXc.lNMWWMK;.oNNd.,0Nd. .dWNl.     '.xWMWWMMMMWMOoxoxddW0lkWkoXMWMMxoNkdKddodc;KOokdOOoodxl0Ol0MWMMMMMMMMM")
    print("MMMWWWWWWWWWWXdldkdldKWW0olxxdlxXMNxckNW0llKWNxckNWWWWXdckNWOldXWKo:lOWWKdlodkdloKWWWWWWWWWWKxdkKkoOKxd00kNMWMW0ON0ONOkk0kdXKk0OKKkOxokNKkKMWWMMMMMMMM")
    print("MMMWWWWWMWWWWWWWNNNWWWWNNWNNNNNNNNNNNNNNNNNNNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKKKXXXXXXXXXXXXXXKXXXKKKKXKXXKXXXXXXXXXXXXXXXXXXXXXXXXXXKKXXXXXNWMMMMMMMMM")
    print("WWWWWWWWMXxxOOOOkkkkkkkkkkkkkkkkxxxxxxxxxxxxxdxxxdddddddddddddddddddddddddddddddddddddddddddddddddodddddddddooddddddddddddddddddddddddddddcoNMWMMMMMWW")
    print("WWWWWWWWMKlxXKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKolXMWMMMMMWW")
    print("WWWMWWWWMKldKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKllXMWWMMMMWW")
    print("WWWWWWWWMKldKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKlcXMWWMMMMMM")
    print("WWWWWWWWMKldKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKlcXMWWMMMMMM")
    print("WWWWWWWWMKcdKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKlcXMWWWMMMMM")
    print("WWWWWWWWMKcdKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKlcXMWWWMMMMM")
    print("WWWWWWWWMKcdKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK0KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKlcXMWWWWWWWW")
    print("WWWWWWWWMKcdKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXXXXXXXXXXXXXXXXXXXXXXXKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKlcXMWWWWWWWW")
    print("WWWWWWWWMKcdKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXXXXXXXXXXXXXXXXXXNNNXXXXXXXXXXXXXXKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKlcXMWWWWWWWW")
    print("WWWWWWWWMKcdKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXXXNNNNNNNNNNNNNNNNNNNNNNNNNNNXXXXXNNXXXXXXKK00KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKlcXMWWWWWWWW")
    print("WWWWWWWWMKcdKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXXXXXXXKK0KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKlcXMWWWWWWWW")
    print("WWWWWWWWMKcdKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXXXXXXXXXKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKlcXMWWWWWWWW")
    print("WWWWWWWWMKcdKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXXXXXXXXK0KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKlcXMWWWWWWWW")
    print("WWWWWWWWMKcdKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXXXXXXXXXXXXK0KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKlcXMWWWWWWWW")
    print("WWWWWWWWMKcdKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXXXXXXXXXXXXXK0KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKl:KMWWWWWWWW")
    print("WWWWWWWWMKcoKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKNNNNNNNNNNNNWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXXXXXXXXXXXK00KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKl:KMWWWWWWWW")
    print("WWWWWWWWMKcoKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXNNNNNNWWWWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNXXXXXXXXXXXXK00KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKl:KMWWWWWWWW")
    print("WWWWWWWWMKcoKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXNNNNWWWWWWWWWMWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNXXXXXXXXXKKK00KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKl:KMWWWWWWWW")
    print("WWWWWWWWMKcoKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKNWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNXXXXXXXXKKKK00KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKl:KMWWWWWWWW")
    print("WWWWWWWWMKcoKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNXXXXXXKKKKK00KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKl:KMWMWWWWWW")
    print("WWWWWWWWMKcoKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXWWWWWWWWWWWWWWWWWWWWWWWWWWWMMWWWNNNNNNNNNNNNNNNXXXXXXKKKKK00KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKl:KMWWWWWWWW")
    print("WWWWWWWWMKcoKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXWMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNXXXXXXXXXKKKKK00KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKl:KMWWWWWWWW")
    print("WWWWWWWWMKcoKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXWMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNXXXXXXXKKKKK00KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKl:KMWWWWWWWW")
    print("WWWWWWWWWKcoKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKNMWWWWWWWWWWWWWWWWWMMWWWWWWWWWWWWWWWWNNNNNNNNXXXXXXXKKKKK000KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKl:KMWWWWWWWW")
    print("WWWWWWWWMKcoKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNXXXXXXKKKKKK000KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKl:KMWWWWWWWW")
    print("WWWWWWWWMKcoKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXWWWMMWWWWWMMWWWWWWWWWWWWWWWWWWWWWWWWWWNNXXXNNNXKKKKKKKK000KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKl:KMWWWWWWWW")
    print("WWWWWWWWMKcoKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXWWWMMMWWWWWWWWWWMMWWWWWWWWWWWWWWWWWWWWWWNXXKOxo;;dKKKK0000KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKl:KMWWWWWWWW")
    print("WWWWWWWWWKcoKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKNWWMMWMMWWWWNXKKKKKXXNWWWWWWWWWWWWWWWWXOxl:,...  .dKK00000KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKl:KMWWWWWWWW")
    print("WWWWWWWWWKcoKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKNNNWWMMWWMN0kkkkkkkdxXMWWWWWWWWWWWWMK:...        :0K0000KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKl:KMWWWWWWWW")
    print("WWWWWWWWWKcoKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK0OOXWMWWMXOkxdoc:;cOWWWWWWWWWWWWWWWNl.         .o000000KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKl:KMWWWWWWWW")
    print("WWWWWWWWMKcoKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK0OxONMWWKxc;,,;cd0NMWWWWWWWWWWWWWWWWXd'.     .;d0KKK000KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKl:KMWWWWWWWW")
    print("WWWWWWWWWK:oKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK0kcoNMWWXXKKKKNWWWWWWWWWWWWWWWWWWWMWWWXkdllod0XXKKK0000KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKl:KMWWWWWWWW")
    print("WWWWWWWWWK:oKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK0k0WMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMWWWWWWXKK000KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKl:KMWWWWWWWW")
    print("WWWWWWWWWK:lKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK0XWMWWWWWWWWWMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNXK00KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKl:KMWWWWWWWW")
    print("WWWWWWWWWK:lKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK0XWWWWWWWWWWMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXK0KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKl:KMWWWWWWWW")
    print("WWWWWWWWWK:lKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXWMWWMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNK0KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKl:KMWWWWWWWW")
    print("WWWWWWWWMK:cKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKWMWWNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNK0KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKl:KWWWWWWWWW")
    print("WWWWWWWWWK:lKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXXXNWWMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWN00KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKl:KMWWWWWWWW")
    print("WWNXXXXNN0:l000KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK0OO0OOO0KNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNK0KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKl:KMWWWWWWWW")
    print("WWXo:ccclc;;cllllllllllllooooooodddddddddxxxxxxxxxxkkkkOOko:;,,;;:ckNMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMWK0KKKKKKKKKKKKKKKKKKKKKKKKKKKKKK0Ok:;KMWWWWWWWW")
    print("WWWKOKXXXXXXXXXXXKKKK0000000000000000000000000OOOOOO0000000d:,,,;:dKWMWWWWWWWWWWWWMMWWWWWWWWWWWWWWWWWWWX0KKKKKKKKKKKKKKKKKKKKKKKKK0Odl:,.. ,KMWWWWWWWW")
    print("WWWWK0NWWWWWWWWWWWNNNNXXXXXKKK000K00000OOkkkxxxxdddddddddool;,:oOXWWWWMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNK0KKKKKKKKKKKKKKKKKKKK0kdc,..      ,KWWWWWWWWW")
    print("WWWWWK0NWWWWWNkclolllccccc::::;;;;;;;;;;,,,,,,,,,,,,;;,,,;;;;;:kWWWWWWMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNKKKKKKKKKKKKKKKKKKOdc,.           ,KWWWWWWWWW")
    print("WWWWWWK0NWWWWW0,.,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,cKWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWX0KKKKKKKKKKKKKOd:'.           ...;KMWWWWWWWW")
    print("WWWWWWN00NWWWWWO'.,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;oKWWMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXK0KKKKKKKKOd:.          ..',:cl,;KMWWWWWWWW")
    print("WWWWWWWN0KWWWWWWx..;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;coxkkkXWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNK0KKKK0xc'          .',:clllll,;KMWWWWWWWW")
    print("WWWWWWWWN00WWWWWNd.';;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,,,;xWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXK0Oo,.        ..,:clllllllll,;KWWWWWWWWW")
    print("WWWWWWWWWOckWWWWWNl.';;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,lKMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWKo'        ..,:clllllllllccl,;KWWWWWWWWW")
    print("WWWWWWWWWO':KWWWWWX:.,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,;xWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWKo'        .':llllllllllllllll,;KWWWWWWWWW")
    print("WWWWWWWWWO':OKWWWWW0;.,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,lXMWWWMWWWWWWWWWWWWWMMWWWWWWWWWWWWXo'        .;cllllllllllllllllll,;KWWWWWWWWW")
    print("WWWWWWWWWO'cOOXWWWWWO,.,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,;kWMWWWWWWWWWWWWWWWWWWWWWWWWWWWWNx'       .';cllllllllllllllllllll,;KWWWWWWWWW")
    print("WWWWWWWWWO'cKOOXWWWWWx..;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,lXMWWWWWWWWWWWWWWWWWWWWWWWWWWWO;.      .':lllllllllllllllllllclll,;KWWWWWWWWW")
    print("WWWWWWWWWO'cKKOOXWWWWNd.';;;;,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,:OWWWWWWWWWWWWWWWWWWWWWWWWWWXl.       .:lllllllllllllllllllcccccl,;KWWWWWWWWW")
    print("WWWWWWWWWO'cKKKOONWWWWNl.,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,o0XMWMWWWWWWWWWWWWWWWWWWWWk,       .;clllllllllllllllllllllcclll,;KWWWWWWWWW")
    print("WWWWWWWWWO'cKKKKO0NWWWWXc.,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,:lOWWWWWWWWMWWWWWWWWWWWWXl.      .,cllllllllllllllllllllllllllll,;KWWWWWWWWW")
    print("WWWWWWWWWO':KKKKKO0NWWWWK;.,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,,oNMWWWWWWWWWWWWWWWWWW0;       .:llllllllllllllllllllllllllllll,;KWWWWWWWWW")
    print("WWWWWWWWWO':KKKKK0O0NWWWWO,.;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,,c0WWWWWWWWWWWWWWWWWWO'      .,clllllllllllllllllllllllllllllll,;KWWWWWWWWW")
    print("WWWWWWWWWO'cKKKKKK0O0NWWWWk'';;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;dNMWWWWWWWWWWWWWWWx.      .;lllllllllllllllllllllllllllllllll,;KWWWWWWWWW")
    print("WWWWWWWWWO':KKKKKKK0O0NWWWNd'';;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,c0MWWWWWWWWWWWWWNd.      .:lllllllllllllllllllllllllllcccclll,;KWWWWWWWWW")
    print("WWWWWWWWWO':KKKKKKKK0O0WWWWNo.,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;xNWWWWWWWWWWWWWd.      .cllllllllllllllllllllllllllllcccccll,;KWWWWWWWWW")
    print("WWWWWWWWW0':KKKKKKKKK0OKWWWWXl.,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,lKMWWWWWWWWWWWx.      'cllllllllllllllllllllllllllllllcccccl,;KWWWWWWWWW")
    print("WWWWWWWWW0':KKKKKKKKKK0OXWWWW0,.;;;;;;;;;;;;;;;;;;;;;;;,;;;;;;;;;;;;;;;;;;;;;,:OWWWWWWWWWWMK,      .:lllllllllllllllllllllllllllllllcccccl,;KWWWWWWWWW")

def leave_music(exit1):
    thebigcheck = 0
    while thebigcheck == 0:
        exit = input("").lower()
        if exit == exit1:
            thebigcheck = 1
            pygame.mixer.Sound.Play()
            os.system('CLS')
            return
        else:
            thebigcheck = 0

def MacInTosh(theTest, looping):
    input("Press enter to play: MACINTOSH PLUS - Lisa Frank 420 / Modern Computer (Please Full screen your window)")
    time.sleep(1)
    os.system('CLS')
    if theTest == "macintosh g" or theTest == "macintosh plus g" or theTest == "macintosh guitar" or theTest == "macintosh plus guitar":
        mac_gsound.play(looping)
        time.sleep(3)
    else:
        mac_osound.play(looping)
        time.sleep(2)
    floral_shoppe_art()
    leave_music("exit")

def enjoy(looping):
    input("Press Enter to play: ST.PEPSI - ENJOY YOURSELF (Please Full screen your window)")
    time.sleep(1)
    os.system('CLS')
    st_pep_enjoy_sound.play(looping)
    time.sleep(3)
    St_Pepsi_Art01()
    leave_music("exit")

def tapestry(looping):
    input("Now playing: Sacred Tapestry - Migration")
    time.sleep(1)
    os.system('CLS')
    tape_sound.play(looping)
    print("I just need a place holder to tell if it's working properly.")
    leave_music("exit")

def tides(looping):
    input("Now playing: HOME - TIDES")
    time.sleep(1)
    print("I couldn't find a picture for tides so i just used the name and artist")
    os.system("CLS")
    tides_sound.play(looping)

    print(" _   _  ___  __  __ _____ ")
    print("| | | |/ _ \|  \/  | ____|   ()")
    print("| |_| | | | | |\/| |  _|  ")
    print("|  _  | |_| | |  | | |___    ()")
    print("|_| |_|\___/|_|  |_|_____|")
    print("                               ")
    print(" _____ ___ ____  _____ ____  ")
    print("|_   _|_ _|  _ \| ____/ ___| ")
    print("  | |  | || | | |  _| \___ \ ")
    print("  | |  | || |_| | |___ ___) |")
    print("  |_| |___|____/|_____|____/ ")

    leave_music("exit")

def come_back_down(looping):
    input("Now playing: Come Back Down - HOME")
    time.sleep(1)
    os.system('CLS')
    come_down_sound.play(looping)

    print(" _   _  ___  __  __ _____ ")
    print("| | | |/ _ \|  \/  | ____|  ()")
    print("| |_| | | | | |\/| |  _|  ")
    print("|  _  | |_| | |  | | |___   ()")
    print("|_| |_|\___/|_|  |_|_____|")
    print("                          ")
    print("  ____ ___  __  __ _____ ")
    print(" / ___/ _ \|  \/  | ____|")
    print("| |  | | | | |\/| |  _|  ")
    print("| |__| |_| | |  | | |___ ")
    print(" \____\___/|_|  |_|_____|")
    print("                         ")
    print(" ____    _    ____ _  __ ")
    print("| __ )  / \  / ___| |/ / ")
    print("|  _ \ / _ \| |   | ' /  ")
    print("| |_) / ___ \ |___| . \  ")
    print("|____/_/   \_\____|_|\_\ ")
    print("                         ")
    print(" ____   _____        ___   _ ")
    print("|  _ \ / _ \ \      / / \ | |")
    print("| | | | | | \ \ /\ / /|  \| |")
    print("| |_| | |_| |\ V  V / | |\  |")
    print("|____/ \___/  \_/\_/  |_| \_|")

    leave_music("exit")

def wavestep(looping):
    input("Now playing: Blank Banskee - WAVESTEP")
    time.sleep(1)
    os.system('CLS')
    wavestep_sound.play(looping)
    blank_banshee_0_art()
    leave_music("exit")

def hyper_object(looping):
    input("Now playing: Blank Banshee - HYPER OBJECT")
    time.sleep(1)
    os.system('CLS')
    hyper_obj_sound.play(looping)
    blank_banshee_0_art()
    leave_music("exit")

def ecozones(looping):
    input("Now playing: Blank Banshee - ECO ZONES")
    time.sleep(1)
    os.system('CLS')
    ecoz_sound.play(looping)
    blank_banshee_1_art()
    leave_music("exit")

def cyber_slums(looping):
    input("Now playing: Blank Banshee - CYBER SLUMS")
    time.sleep(1)
    os.system('CLS')
    cyb_slum_sound.play(looping)
    blank_banshee_1_art()
    leave_music("exit")

def moonlight(looping):
    input("Now playing: S U R F I N G - MOONLIGHT")
    time.sleep(1)
    os.system('CLS')
    moon_sound.play(looping)
    surfing_art()
    leave_music("exit")

def brain_drain(looping):
    input("Now playing: Brain Drain - Sun Parade")
    time.sleep(1)
    os.system('CLS')
    drain_sound.play(looping)
    brain_drain_art()
    leave_music("exit")

jeeg = 0
loop_req = 0
apply_loop = 0

#make lines that write to a program on opening?

while jeeg == 0:
    print("What do you wish to listen to?")
    theTest = input("").lower()
    if theTest == "show" or theTest == "list" or theTest == "What can I listen to?":
        print("Current available Tracks:")
        print("")
        #make lines that read from a program
        file = open("songlist.txt", "r")
        for line in file:
            print(line)
        print("")
    elif theTest == "macintosh" or theTest == "macintosh plus" or theTest == "macintosh g" or theTest == "macintosh plus g" or theTest == "macintosh guitar" or theTest == "macintosh plus guitar":
        time.sleep(2)
        os.system('CLS')
        loop_req = input("Do you want it to loop?").lower()
        if loop_req == "yes" or loop_req == "y":
            apply_loop = (-1)
        else:
            apply_loop = 0
        MacInTosh(theTest, apply_loop)
    elif theTest == "enjoy yourself":
        time.sleep(2)
        os.system('CLS')
        enjoy()
    elif theTest == "exit":
        print("Press Enter to Exit.")
        input("")
        jeeg = 1
    elif theTest == "tides":
        time.sleep(2)
        os.system("CLS")
        tides()
    elif theTest == "egg":
        #winsound.playSound("sounds/egg.wav", 0)
        print("egg")
    elif theTest == "clear":
        os.system("CLS")
    elif theTest == "come back down":
        time.sleep(1)
        os.system('CLS')
        come_back_down()
    elif theTest == "shader" or theTest == "sacred tapestry" or theTest == "migration" or theTest == "sacred":
        time.sleep(1)
        os.system('CLS')
        loop_req = input("Do you want it to loop?").lower()
        if loop_req == "yes" or loop_req == "y":
            apply_loop = -1
        else:
            apply_loop = 0
        tapestry(apply_loop)
    elif theTest == "wavestep" or theTest == "blank banshee wavestep":
        time.sleep(1)
        os.system('CLS')
        loop_req = input("Do you want it to loop?").lower()
        if loop_req == "yes" or loop_req == "y":
            apply_loop = -1
        else:
            apply_loop = 0
        wavestep(apply_loop)
    elif theTest == "hyper object":
        time.sleep(1)
        os.system('CLS')
        loop_req = input("Do you want it to loop?").lower()
        if loop_req == "yes" or loop_req == "y":
            apply_loop = -1
        else:
            apply_loop = 0
        hyper_object(apply_loop)
    elif theTest == "eco zones" or theTest == "eco":
        time.sleep(1)
        os.system('CLS')
        loop_req = input("Do you want it to loop?").lower()
        if loop_req == "yes" or loop_req == "y":
            apply_loop = -1
        else:
            apply_loop = 0
        ecozones(apply_loop)
    elif theTest == "cyber slums":
        time.sleep(1)
        os.system('CLS')
        loop_req = input("Do you want it to loop?").lower()
        if loop_req == "yes" or loop_req == "y":
            apply_loop = -1
        else:
            apply_loop = 0
        cyber_slums(apply_loop)
    elif theTest == "surfing" or theTest == "moonlight":
        time.sleep(1)
        os.system('CLS')
        loop_req = input("Do you want it to loop?").lower()
        if loop_req == "yes" or loop_req == "y":
            apply_loop = -1
        else:
            apply_loop = 0
        moonlight(apply_loop)
    elif theTest == "brain drain" or theTest == "sun parade":
        time.sleep(1)
        os.system('CLS')
        loop_req = input("Do you want it to loop?").lower()
        if loop_req == "yes" or loop_req == "y":
            apply_loop = -1
        else:
            apply_loop = 0
        brain_drain(apply_loop)
    else:
        print("I didn't understand that.")
